### ISSUE TITLE
cryptonite-0.1 can't link its test suite

### ISSUE THREAD

**Issue by peti** [haskell-crypto/cryptonite#1]
Citing from http://hydra.cryp.to/build/887540/log/raw:

```
Linking dist/build/test-cryptonite/test-cryptonite ...
/tmp/nix-build-haskell-cryptonite-0.1.drv-0/cryptonite-0.1/dist/build/libHScryptonite-0.1-7JEy8lnj4Z02y2at3QipFc-ghc7.10.1.so: undefined reference to `cryptonite_p256_point_mul'
/tmp/nix-build-haskell-cryptonite-0.1.drv-0/cryptonite-0.1/dist/build/libHScryptonite-0.1-7JEy8lnj4Z02y2at3QipFc-ghc7.10.1.so: undefined reference to `cryptonite_p256_modinv'
/tmp/nix-build-haskell-cryptonite-0.1.drv-0/cryptonite-0.1/dist/build/libHScryptonite-0.1-7JEy8lnj4Z02y2at3QipFc-ghc7.10.1.so: undefined reference to `cryptonite_p256_to_bin'
collect2: error: ld returned 1 exit status
```

**Comment by peti** [comment]
Will you release a new version?

**Comment by vincenthz** [comment]
done 0.2 is out.

out of curiosity, is there a reason why only nix is finding this problem ? is it some system linker settings ?

**Comment by peti** [comment]
I have no idea. Our linker configuration is a little special: we hard-code rpaths for everything, we reject paths outside of `/nix/store`, etc., so clearly some intelligence has gone into that setup. Why it has the effect it does in this particular case, however, I don't know.
