### ISSUE TITLE
Shouldn't Crypto.Tutorial be runnable?

### ISSUE THREAD

**Issue by qrilka** [haskell-crypto/cryptonite#106]
The code listed in http://hackage.haskell.org/package/cryptonite-0.20/docs/Crypto-Tutorial.html contains some undefined `Key` and why define `secretKey` is defined with no example how it could be used?
Example which could be run by user makes more sense imo.

**Comment by tdietert** [comment]
Hopefully this would be resolved by #145

**Comment by ocheron** [comment]
@tdietert's code is now runnable:
http://hackage.haskell.org/package/cryptonite/docs/Crypto-Tutorial.html
