### ISSUE TITLE
No included function for `Digest a -> ByteString`? Byteable shows `No instance for (Byteable (Digest SHA256))`.

### ISSUE THREAD

**Issue by cyrbon** [haskell-crypto/cryptonite#107]
I have `byteable-0.1.1` and `cryptonite-0.19`. It seems that digestToByteString was depricated and `toBytes` from `byteable` has no instance for digest:

```
 let digest :: Digest SHA256 = hash ("hello" :: ByteString)
                     bs :: ByteString = toBytes digest
```

Will throw:

```
    * No instance for (Byteable (Digest SHA256))
        arising from a use of `toBytes'
    * In the expression: toBytes digest
      In an equation for `bs': bs = toBytes digest
      In the expression:
        do { strName <- B.getLine;
             case readAlgo strName of {
               Just (SomeHA a) -> f a
               Nothing -> print "nope" };
             let digest :: Digest SHA256 = hash ("hello" :: ByteString)
                 bs = toBytes digest;
             return () }
```

**Comment by cyrbon** [comment]
Perhaps, instead of `toBytes` from `Data.Byteable`, users can be pointed to `convert` from `Data.ByteArray`? `convert` works fine.

**Comment by wereHamster** [comment]
I was looking how to create a hash as a `ByteString`, so I can feed it into `base16-bytestring` to encode it as a hex-string. The example in the `Crypto.Hash` module only shows how to use `show`.

Looking at some of the related packages, it might actually be easier to use `withBytePtr` and `showHexadecimal` (from `Data.Memory.Encoding.Base16`). More examples and pointers to related packages would be useful here. It's not obvious that `Digest` is a newtype around `Bytes`, only after looking at the source. But maybe you consider that an implementation detail and don't want that to leak to the users?

**Comment by tekul** [comment]
@wereHamster Instead of using `base16-bytestring` you should be able to use `convertToBase Base16` from [`Data.ByteArray.Encoding`](http://hackage.haskell.org/package/memory-0.13/docs/Data-ByteArray-Encoding.html). `Digest` is already a `ByteArrayAccess` instance so you can pass it directly to this function.

**Comment by tekul** [comment]
Looking at the build, we have a test dependency on `byteable` which seems to be unused. Removing that would perhaps make it clearer that cryptonite doesn't provide any Byteable instances.

**Comment by tekul** [comment]
I removed the dependency. I'm going to close this since there's nothing specific that needs to be changed.
