### ISSUE TITLE
Any valid AES key size works for AES256?

### ISSUE THREAD

**Issue by tmciver** [haskell-crypto/cryptonite#113]
I'm initializing an `AES256` `Cipher` as seen here: https://github.com/unisonweb/unison/blob/5b22506804c844bc09c05673061d93c8b6d8281f/node/src/Unison/Runtime/Cryptography.hs#L62 but I found that there is no problem with using a 128-bit key.  Is this expected behavior?

I see that the key length for `AES256` is fixed here: https://github.com/haskell-crypto/cryptonite/blob/47cb6ebdeaa6149b9cd2e70422e037ace3cb33ae/Crypto/Cipher/AES.hs#L45 but it is apparently not checked.

**Comment by vincenthz** [comment]
Looks like a small bug where it will give you a AES128 context wrapped in `AES256` because of the 128 bit key. care to make a fix ?

**Comment by tmciver** [comment]
Sure, I'll take a shot at it.  A question though: do the `AES128`, `AES192` and `AES256` types represent "keys"?  You mentioned "context" (as do the comments); is that something different than just a key?

**Comment by vincenthz** [comment]
yes, the first step of AES is preparing a key (128, 192, 256 bits) into a many rounds key (12 to 14 128 bits keys) which is what is called context here.
