### ISSUE TITLE
Integrated ECDSA

### ISSUE THREAD

**Issue by kazu-yamamoto** [haskell-crypto/cryptonite#120]
I would like to have an integrated ECDSA for basic ECDSA, Ed25519 and Ed448.

**Comment by vincenthz** [comment]
ECDSA doesn't exist for Ed25519 and Ed448. What do you want to do ?

**Comment by ocheron** [comment]
Well for example there is [draft-ietf-curdle-pkix](https://datatracker.ietf.org/doc/draft-ietf-curdle-pkix/) being defined. Some time ago I looked if it was easy to add EdDSA in x509-* but stopped at the first design choice: how to map the new OIDs to the existing `SignatureALG` data type.

More generally there is already code duplication in tls and x509-validation related to signatures. This includes RSA and DSA too. So there might be room for a common API somewhere.

**Comment by vincenthz** [comment]
@ocheron: A common signature system is not as simple as expected. Also I'm not sure that's what @kazu-yamamoto is asking about.

**Comment by kazu-yamamoto** [comment]
Recently, common technical terms mean:

- Curve 25599 - EC framework
- X 25599 - ECDH based on Curve 25599
- Ed 25599 - ECDSA based on Curve 25599

So, I misunderstood that `Ed25599` in cryptonite contains ECDSA.

**Comment by kazu-yamamoto** [comment]
Oh, `Ed25599` contains ECDSA but `Ed488` contains ECDH.
The naming is confusing to me.

**Comment by vincenthz** [comment]
`Ed25519` is using `EdDSA` not `ECDSA`.

* ECDSA : signature system elliptic curve, that is non deterministic (random number needed when creating a new signature)
* EdDSA : signature system on elliptic curve, deterministic using Schnorr signature.
* ECDH : Elliptic curve Diffie Hellman. given a couple of `(sk,pk)A` and `(sk,pk)B`, you can create a shared secret : `ecdh(skA, pkB) == ecdh(skB, pkA)`

**Comment by kazu-yamamoto** [comment]
Sorry for my ignorance!

Anyway, isn't it the name of `Crypto.PubKey.Ed448`, which provides ECDH not EdDSA, confusing?

**Comment by kazu-yamamoto** [comment]
With the correct knowledge, my request is providing EdDSA API for Ed25519 and Ed448.

**Comment by ocheron** [comment]
I just want to point out that all EdDSA variants and test vectors from [RFC 8032](https://www.rfc-editor.org/rfc/rfc8032.txt) (just released) are supported when I combine some work for #76 with the new C implementation mentioned in #84. Preliminary result is published here: [ocheron/eddsa](/ocheron/cryptonite/commits/eddsa).

**Comment by centromere** [comment]
> Anyway, isn't it the name of `Crypto.PubKey.Ed448`, which provides ECDH not EdDSA, confusing?

This was fixed in #128.

**Comment by kazu-yamamoto** [comment]
Thanks. Let's close.
