### ISSUE TITLE
X448

### ISSUE THREAD

**Issue by kazu-yamamoto** [haskell-crypto/cryptonite#121]
I would like to have X488 integrated into ECIES.

Question: Why are Curve25519.hs, Ed25519.hs adn Ed488.hs on Crypto.PubKey instead of Crypto.PubKey.ECC?

**Comment by vincenthz** [comment]
`Crypto.PubKey.ECC` just provide NIST-like Weirstrass elliptic curve support, so it's eventually going away replaced by the choose-your-backend friendly `Crypto.ECC`.

All the implementations/bindings over ECC (Curve25519, Ed25519, Ed448, P256) will move to `Crypto.ECC` and `Crypto.PubKey` will only have high level public key protocol
