### ISSUE TITLE
Discrete Logarithm Integrated Encryption Scheme (DLIES)

### ISSUE THREAD

**Issue by kazu-yamamoto** [haskell-crypto/cryptonite#122]
Probably, we should define `deriveEncrypt` and `deriveDecrypt` in DLIES.

I would also like to have pre-defined DH parameters defined in [RFC7919](https://tools.ietf.org/html/rfc7919).

**Comment by vincenthz** [comment]
I suppose we could add this, but ECIES is clearly superior on every points compared to DLIES, and DLIES is not terribly much forward looking. Is there a reason to add this in cryptonite now compared to doing the TLS DH support in TLS ?

As to pre-defined DH parameters, maybe it make sense to defined them in TLS ?

**Comment by kazu-yamamoto** [comment]
> I suppose we could add this, but ECIES is clearly superior on every points compared to DLIES, and  DLIES is not terribly much forward looking. Is there a reason to add this in cryptonite now compared to doing the TLS DH support in TLS ?

TLS 1.3 requires pre-defined DH parameters defined in RFC7919 and I would like to use a similar DH API as ECDH API.

> As to pre-defined DH parameters, maybe it make sense to defined them in TLS ?

OK. I will implement this in `tls` first. In review process of merging my TLS 1.3 implementation, we can decide which DH-related code should go, `tls` or `cryptonite`.
