### ISSUE TITLE
Generated primes are of incorrect size

### ISSUE THREAD

**Issue by colatkinson** [haskell-crypto/cryptonite#124]
Sometimes when generating primes, they are larger than the selected bit size.
For example, when generating a prime of 5 bits, the output will be 37 (6 bits), 67 for 6 bits, or 257 for 8 bits.

**Comment by tekul** [comment]
Hi, could you give an example of the code you are using please?

**Comment by colatkinson** [comment]
Using current master:

```
Prelude Crypto.Number.Prime> generatePrime 5
29
Prelude Crypto.Number.Prime> generatePrime 5
37
Prelude Crypto.Number.Prime> generatePrime 8
257
Prelude Crypto.Number.Prime> generateSafePrime 5
227
```

The problem persists in compiled code.

Based on looking at the code, I think that this is probably caused by the fact that `findPrimeFrom` and `findPrimeFromWith` do not perform any checks on the size of their results. A simple solution would be to just perform a check in `generatePrime` and `generateSafePrime` to check if the result is less than 2^bits, although I'm not sure if a better method exists.

**Comment by tekul** [comment]
My guess would be that for the expected crypto-related use cases, the function would only be used to generate large primes (to generate an RSA key, for example). For the large number of bits that would be used, the chance of overflowing by an extra bit is small and doesn't have a detrimental effect in any case. @vincenthz can probably clarify.

**Comment by colatkinson** [comment]
It does have a detrimental effect in that if a piece of code is generating an n-bit key, runs code to generate an n-bit key, and gets an (n+1)-bit key, the library is introducing room for unforeseen bugs. If I want to e.g. send a public key with a strict protocol and it doesn't fit into the allotted space, then my application is broken, or at a minimum has to relax some guarantees.

Given that a fix is basically just an if statement, I'm working on a PR.

**Comment by vincenthz** [comment]
yes @tekul 's explanation is the right one, no effort is made to generate a key of a specific bit size, but of at *least* a specific bit size. I don't think generating a number of 5 to 8 bits is what this function was designed for.

One obvious thing, is that we clearly lack documentation here

**Comment by ocheron** [comment]
@vincenthz I have a related question (somewhat): while looking at generation of DHParams I noticed that the slow operation is `generateSafePrime`. The current implementation in `findPrimeFromWith` does not call GMP like `findPrimeFrom` does. Instead it tests every odd integer successively.

Is this on purpose?

Calling `gmpNextPrime n` instead of `isProbablyPrime n` seems to make it quicker (on average).  But if there is a good reason for a slower implementation (like accuracy / number of iterations), then I think it should be documented too.

**Comment by ocheron** [comment]
#125 has been merged to fix small bit sizes.

I may open a PR about implementation difference between `findPrimeFromWith` and `findPrimeFrom` in the future.
