### ISSUE TITLE
how to get HMAC-SHA1 digest octet string [Question]

### ISSUE THREAD

**Issue by yuanw** [haskell-crypto/cryptonite#129]
I am trying to implement oauth 1.0 a in haskell. As part of it, i need to use HMAC-SHA1 to generate "oauth_signature", The [specs](https://tools.ietf.org/html/rfc5849#section-3.4.2) requires octet string of digest result, `show .  HMAC.hmacGetDigest` seems return hex version of digest. How should I get  octet string of digest? 

Thank you so much!

**Comment by vincenthz** [comment]
from the `memory` package, you can use `Data.ByteArray` to do a `convert myHmac` to a binary representation of your choice.

**Comment by centromere** [comment]
```haskell
let rawBytes = Data.ByteArray.convert . HMAC.hmacGetDigest $ foo
```
Note also that after you get the raw bytes, you'll need to base64 encode them, as per the spec.

**Comment by vincenthz** [comment]
@centromere I don't think you need to hmacGetDigest there. `HMAC` has a `ByteArrayAccess` instance.

Also if you need base64 encoding, don't convert to binary first. just use:

```haskell
   let base64Bytes = Data.ByteArray.Encoding.convertToBase Data.ByteArray.Encoding.Base64 foo
```

**Comment by centromere** [comment]
Oh wow, I didn't know that existed. Thanks.

**Comment by yuanw** [comment]
thank you for quick response, should I close this issue?

**Comment by vincenthz** [comment]
If you're satisfied with the resolution, then yes :)
