### ISSUE TITLE
Add argon2

### ISSUE THREAD

**Issue by ocharles** [haskell-crypto/cryptonite#130]
Following on from https://github.com/ocharles/argon2/issues/10. I had a go at this, adding bits of `phc-winner-argon2` into `cbits`. Unfortunately, it doesn't look like it's going to be that simple. The `blake2` API in `cbits` is different from the required `blake2` api in `phc-winner-argon2`. This work looks to be beyond me, so I don't think I'll be able to submit a PR.

**Comment by vincenthz** [comment]
Thanks @ocharles, I'll have a look at the cbits. @centromere do you have any idea about the differences between the blake2 implementation ?

We also badly need a better method to track the upstream source of different projects than what we have now, I'll see what I can do about having a lightweight tracking method.

**Comment by centromere** [comment]
@vincenthz The blake2 code was lifted directly from https://github.com/BLAKE2/BLAKE2. I'm not sure what the differences are.

**Comment by ocharles** [comment]
From having a look at that repo, it looks like it's just that the code we have in `cryptonite` has bit-rotted - it's no longer the current branch of `BLAKE2`. Updating that might actually be sufficient. I was getting an error about a missing `blake2b_long` symbol, but now that I look at the code again, I see https://github.com/P-H-C/phc-winner-argon2/blob/b427f8ff98fded23612ef9e44c0c14922d2c0899/src/blake2/blake2b.c#L439 - so we should probably just lift that function directly from the `phc-winner-argon2` source into some new `cbits`.

**Comment by centromere** [comment]
@ocharles Would updating the code to the latest available in https://github.com/BLAKE2/BLAKE2 be sufficient?

**Comment by vincenthz** [comment]
I've lifted all the C bits through #138, so that should be relatively easy to add argon2 now

**Comment by vincenthz** [comment]
@ocharles unless you want to retry to do it yourself, are you happy for me to take the argon2 hs file in your package and move them to cryptonite ?

**Comment by ocharles** [comment]
Go right ahead!

**Comment by ocharles** [comment]
Vincent Hanquez <notifications@github.com> writes:

> @ocharles unless you want to retry to do it yourself, are you happy
> for me to take the argon2 hs file in your package and move them to
> cryptonite ?

Go right, ahead!

**Comment by vincenthz** [comment]
released in 0.22
