### ISSUE TITLE
Allow unpacking Digest or at least make instance Binary for it

### ISSUE THREAD

**Issue by wdanilo** [haskell-crypto/cryptonite#146]
Hi! I want to use `Digest SHA1` to be serialized in a "header" of my sructure. I cannot do it curently and cannot define the instance by myself, because neither constructor is exported nor Digest derives Generics.

**Comment by vincenthz** [comment]
Hi @wdanilo, have a look at #129 . Digest SHA1 have instances like HMAC

**Comment by wdanilo** [comment]
I don't think it solves my problem. I can use `ByteArrayAccess` to encode `Digest` to `ByteArray`, however it is impossible to decode it back to `Digest`, am I right?

**Comment by vincenthz** [comment]
you can convert back using `Crypto.Hash.digestFromByteString` which has been generalized since the initial version to take any `ByteArrayAccess`.

**Comment by wdanilo** [comment]
@vincenthz cool! Thank you for help! :)
