### ISSUE TITLE
Argon2 test failure

### ISSUE THREAD

**Issue by ocheron** [haskell-crypto/cryptonite#148]
On Linux 32 bits I have this warning:
```
Crypto/KDF/Argon2.hs:89:19: warning: [-Woverflowed-literals]
    Literal 4294967295 is out of the Int range -2147483648..2147483647
```

and then a test failure:
```
Argon2
  KATs
    1:                    FAIL
      expected: CryptoPassed "\193b\136\&2\DC4}\151 \197\189\FS\253a6pxr\159m\251o\143\234\159\249\129X\224\215\129n\208"
       but got: CryptoFailed CryptoError_OutputLengthTooBig
```

Should `outputMaxLength` be changed to 0x7fffffff ?

**Comment by tekul** [comment]
Hmm. I don't know much about argon2, but even that seems a bit on the large side :-). The example they give is only 32 bytes in length. https://github.com/P-H-C/phc-winner-argon2. Isn't there a hard limit on the size, based on the hash function that is being used?

**Comment by ocheron** [comment]
In the specification this must be the tag length τ:
> any integer number of bytes from 4 to 2^32-1.

On a 32-bit architecture this will be implicit, and the test could just be removed.
But I don't see anything to check the actual Int size from a CPP directive.

So this is either limit to 0x7fffffff or promote to Int64 to do this check.
Using 0x7fffffff is simpler and should be enough for anybody.

**Comment by tekul** [comment]
Ok, makes sense to me. I see the code checks if the [output length is greater the hash size](https://github.com/haskell-crypto/cryptonite/blob/master/cbits/argon2/core.c#L85) and loops to fill the extra space. Having such a large maximum still seems unnecessary to me, though, given that there isn't any obvious gain in security and any order of magnitude more than the Blake2 hash size would almost certainly be a mistake on the user's part.

**Comment by ocheron** [comment]
Modification pushed, thanks for looking too.
