### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by kazu-yamamoto** [haskell-crypto/cryptonite#151]
The following code causes segfault: https://gist.github.com/kazu-yamamoto/25b7b4ee7884e30a93355e20f5efe0ac

It seems to me that `getRandomBytes` causes segufault.

Relating to: https://github.com/vincenthz/hs-tls/pull/205

**Comment by ocheron** [comment]
That's because `withTempPoint` uses `scalarSize` instead of `pointSize`.

**Comment by kazu-yamamoto** [comment]
Cool!

I will send a PR to fix this.
