### ISSUE TITLE
New Hackage Release?

### ISSUE THREAD

**Issue by SamProtas** [haskell-crypto/cryptonite#153]
Any idea when you might make another Hackage/Stackage release?

I have a library depending on `cryptonite`, including the recently merged Twofish PR. Right now I'm building off the latest master commit which I'd prefer to fix when possible.

**Comment by ocheron** [comment]
You can now use [cryptonite-0.23](http://hackage.haskell.org/package/cryptonite-0.23).

**Comment by SamProtas** [comment]
Thanks!
