### ISSUE TITLE
`generateBetween` excludes upper bound if lower bound is 1

### ISSUE THREAD

**Issue by dimitri-xyz** [haskell-crypto/cryptonite#154]
The description of `generateBetween` states that we can use it to:

> generate a number between the inclusive bound [low,high].

However, something went astray on [commit bc4a55f](https://github.com/haskell-crypto/cryptonite/commit/bc4a55ff746043e3f02486d434cdf6480a62de6f) and there is an exception introduced when the lower bound 1 one that makes it so that the upper bound is *excluded* when that happens. I do not see any reason for this change, it seems it should be reverted. The previous simpler version:

```haskell
generateBetween :: MonadRandom m => Integer -> Integer -> m Integer
generateBetween low high = (low +) <$> generateMax (high - low + 1)
```
is always correct assuming so is `generateMax`.

**Comment by ocheron** [comment]
Yes I couldn't find any reason either.
EC point generation uses `generateBetween 1 (n - 1)` and `n - 1` is to be included.

Do you want to send a PR?

**Comment by ocheron** [comment]
PR merged, thanks.
