### ISSUE TITLE
multiple definition of `gmtab'

### ISSUE THREAD

**Issue by snoyberg** [haskell-crypto/cryptonite#16]
I got both a [user report](http://stackoverflow.com/questions/30954365/docker-yesod-linking-failure) for this problem, and had a build of my own fail. It appears like both cipher-aes and cryptonite provide the same linker name, which causes a conflict. Would it be possible to rename this in cryptonite so- while the transition to cryptonite is not yet complete- we can link in both libraries?

**Comment by vincenthz** [comment]
thanks for the report, this was exported for no reason in the first place (released as cipher-aes 0.2.11 and cryptonite 0.5). I also made sure that all the function are properly prefixed in cryptonite (there was a few), so that should prevent any further problem.

**Comment by snoyberg** [comment]
Thanks for the quick response!
