### ISSUE TITLE
Export Crypto.KDF.BCrypt.rawHash or similar

### ISSUE THREAD

**Issue by mat8913** [haskell-crypto/cryptonite#177]
I would find it really useful to get a raw (not base64 encoded) output from bcrypt.

As far as I can tell, none of the other bcrypt libraries on Hackage offer this, but this library seems to be in the best position to do so as you already have a rawHash function.

**Comment by tekul** [comment]
Could you explain what you need this for please? It doesn't sound like a common requirement. It should be easy to just base64 decode the salt/hash combination and the overhead will be negligible compared with the time taken by bcrypt itself.

**Comment by mat8913** [comment]
I'm implementing a deterministic password generator, similar to https://www.pwdhash.com/ but using bcrypt instead of md5. Some websites have limitations on what characters can be in passwords, so I apply a custom digest function to the raw output of bcrypt.

Currently, I am doing as you suggest and base64 decoding the output. I just thought since the rawHash function is there, it would be nice to use it.

**Comment by tekul** [comment]
If you are just looking for a slow hash function, then you could consider using the `hash` function from the Argon2 module. This also has a C implementation backing it, whereas the bcrypt code really needs some optimization.

**Comment by tekul** [comment]
Closing, as it seems like a rare use case and there are other options available.
