### ISSUE TITLE
ECDH and ECIES failures

### ISSUE THREAD

**Issue by ocheron** [haskell-crypto/cryptonite#178]
ECIES is supposed to check that ECDH result is not the point at infinity but this is not currently possible from the type class EllipticCurveDH.

X25519 has cofactor 8 and some (rare) weak points result in zeros when multiplied by any scalar.
This is because scalars are divisible by 8 and the all-zero result encodes both ∞ and (0,0), which has order 2.

For example:
```
> :m Crypto.ECC Crypto.Error Data.Proxy Data.ByteArray Crypto.PubKey.Curve25519
> let curve = Proxy :: Proxy Curve_X25519
> s <- curveGenerateScalar curve
> let CryptoPassed p = publicKey (pack [0x5f,0x9c,0x95,0xbc,0xa3,0x50,0x8c,0x24,0xb1,0xd0,0xb1,0x55,0x9c,0x83,0xef,0x5b,0x04,0x44,0x5c,0xc4,0x58,0x1c,0x8e,0x86,0xd8,0x22,0x4e,0xdd,0xd0,0x9f,0x11,0x57] :: Bytes)
> convert (ecdh curve s p) :: Bytes
"\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL"
```

To detect the situation one option would need to change EllipticCurveDH and ECIES functions with CryptoFailable results.

Another option is to raise an exception.
Some implementations of `ecdh` already fail when the scalar is zero:
```
> :m Crypto.ECC Data.Proxy Data.ByteArray
> let curve = Proxy :: Proxy Curve_P384R1
> let s = read "Scalar 0" :: Scalar Curve_P384R1
> p <- keypairGetPublic `fmap` curveGenerateKeyPair curve
> convert (ecdh curve s p) :: Bytes
"*** Exception: Crypto/ECC.hs:152:9-44: Irrefutable pattern failed for pattern Point x _
```
(but an exception from the private scalar is much less an issue than from the public point).

**Comment by vincenthz** [comment]
I think this is one of those things where it's not a problem to break API, if it's border line a security problem or something that is painful to deal with

**Comment by ocheron** [comment]
OK great, so this is also a change to include before releasing tls HEAD.

**Comment by vincenthz** [comment]
I was looking at this, probably can make another method in the class, tentatively called 'ecdhFailable', that return a CryptoFailable, and have ecdh defined by default as `ecdh = throwCryptoError . ecdhFailable`.

I haven't made a PR because I'm not sure how to call this.

**Comment by ocheron** [comment]
With a new function we can keep the non-contributory behaviour of X25519/X448 for those who know what they're doing.

My naming ideas are:
```haskell
ecdh     :: proxy curve -> Scalar curve -> Point curve -> SharedSecret
ecdhSafe :: proxy curve -> Scalar curve -> Point curve -> CryptoFailable SharedSecret
```
or better if we can swap: 
```haskell
ecdhRaw :: proxy curve -> Scalar curve -> Point curve -> SharedSecret
ecdh    :: proxy curve -> Scalar curve -> Point curve -> CryptoFailable SharedSecret
```

**Comment by vincenthz** [comment]
I've fined with either those suggestions. There's an advantage to ecdh/ecdhSafe in term of compat, but the safe by default is also an interesting proposition.

I'm tending toward ecdh/ecdhRaw (safe by default) since I don't see breaking API/compat as a big problem in haskell

**Comment by ocheron** [comment]
OK, I have some pieces and should be able to finish a PR in 1-2 days.
Unless you already have something.
