### ISSUE TITLE
Padding - ZERO doesn't unpad?

### ISSUE THREAD

**Issue by nghamilton** [haskell-crypto/cryptonite#192]
Padding with ZERO and attempting to unpad results in Nothing.

`unpad (ZERO 16) $ pad (ZERO 16) "test" :: Maybe ByteString`

Is the expected behaviour really to only return Just bytes if the bytes are mod padding length?

**Comment by centromere** [comment]
If it was my intention to send you a message with two `\NUL` bytes and we're using zero padding, how should the algorithm behave?

**Comment by nghamilton** [comment]
Hmm.. :) Thanks.
