### ISSUE TITLE
How to check if AES-NI is supported at runtime?

### ISSUE THREAD

**Issue by donatello** [haskell-crypto/cryptonite#194]
Hi,

I am trying to write a file encryption application. I want to be able to automatically choose ciphers based on hardware support for AES-NI instructions. Is there a way to do this at runtime?

**Comment by vincenthz** [comment]
There isn't right now, but that would be a really good idea to have. at the moment everything is in `cryptonite_cpu.c`, and it should be just a matter of exposing a new module `Crypto.System.Cpu` where we can expose some of those things like aesni and pclmuldq that call into cpuid for x86

**Comment by ocheron** [comment]
Added in #281.
