### ISSUE TITLE
EllipticCurveFoo instances for Ed25519?

### ISSUE THREAD

**Issue by jml** [haskell-crypto/cryptonite#197]
Hello!

I wrote a [library](http://hackage.haskell.org/package/spake2) that implements the [SPAKE2 protocol](http://www.di.ens.fr/~mabdalla/papers/AbPo05a-letter.pdf).

To do this, I needed something like `EllipticCurveArith`, except with more flexibility. Specifically, support for:

1. inverting and/or subtracting points
2. encoding & decoding scalars

I also needed an implementation for Ed25519 (which I gather is _not_ the same thing as X25519, but please do correct me if I'm wrong).

Because I didn't know what I was doing when I implemented spake2, I made my own type classes (see https://github.com/jml/haskell-spake2/blob/master/src/Crypto/Spake2/Group.hs), rather than extending `EllipticCurveArith`. However, I think it should be fairly straightforward to replace these with something that extends `EllipticCurveArith`.

The pure Haskell implementation of those interfaces for Ed25519 lives here: https://github.com/jml/haskell-spake2/blob/master/src/Crypto/Spake2/Groups/Ed25519.hs

I guess this issue is a few questions:

1. would you be open to extending `EllipticCurveArith` to have support for encoding & decoding scalars, and for inverting / subtracting points?
2. would you like that as a new typeclass, or as a change to an existing one?
3. would you like an implementation of the various `EllipticCurveFoo` instances for Ed25519?

Thanks,
jml

**Comment by vincenthz** [comment]
I'm fine with the idea of adding more things etc.. althought one major downside of this, is the confusion related to Ed25519 which is a signature scheme, and the curve associated to it (which is what you're talking about here)

Also I've made another pure haskell implementation months ago and it's available at https://github.com/input-output-hk/cardano-crypto/blob/master/src/Crypto/ECC/Edwards25519.hs

We could start by providing the arithmetic necessary, and see if we can generalize the operation into class. but as a starting point it's probably easier to just simple functions.

**Comment by jml** [comment]
Thanks!

>  is the confusion related to Ed25519 which is a signature scheme, and the curve associated to it

Yes. This was very confusing to me as a beginner to crypto. 

> Also I've made another pure haskell implementation months ago

Cool! I've got no particular attachment to my implementation.

> We could start by providing the arithmetic necessary, and see if we can generalize the operation into class. but as a starting point it's probably easier to just simple functions.

This seems like a good approach. The class approach made sense for me, as the SPAKE2 has no particular ties to the Edwards 25519 (or indeed, ECC in general. It just needs abelian groups.) However, adding simple functions is a good approach for a general purpose library with actual users.

What's the next step?

**Comment by ocheron** [comment]
Another approach is to expose more of the arithmetic primitives that already exist in ed25519-donna C implementation. I've been exploring this, with now some interesting results about scalar multiplication (speed + constant time).

Nevertheless I think a pure-Haskell implementation can be interesting too, especially if there's a way to generalize to any twisted Edwards curve.

**Comment by ocheron** [comment]
I opened #202 with most of what is necessary.

The only thing left is scalar encoding/decoding because I'm not sure of what to do about endianness. NIST curves have big-endian numbers in ECDSA private keys, and my understanding is that SPAKE2 uses that too for Ed25519. However EdDSA libraries use little-endian. So I'll rather wait to see more use cases and/or standards about that aspect.

**Comment by ocheron** [comment]
Closing: after addition of `Crypto.ECC.Edwards25519`, #225 is open to discuss extension of `EllipticCurve` classes.
