### ISSUE TITLE
Data.Proxy instead of undefined?

### ISSUE THREAD

**Issue by michalrus** [haskell-crypto/cryptonite#198]
It doesn’t matter much, maybe for not looking scary to readers, but `Data.Proxy` could be used here instead of `undefined`:

https://github.com/haskell-crypto/cryptonite/blob/3c087f0f4462df606524083699119445bb81dfa6/Crypto/Random/Entropy/Backend.hs#L33

Or is there a good reason not to do that?

**Comment by tekul** [comment]
`Data.Proxy` was only introduced in GHC 7.8 and cryptonite used to support earlier version. I think 7.8 is the minimum version we support now, so it might be a good idea to remove use of `undefined` from the codebase.

**Comment by vincenthz** [comment]
@tekul is absolutely right, however careful with issue related to compat

**Comment by michalrus** [comment]
Thank you!

**Comment by michalrus** [comment]
It seems like there are a couple more places?

https://github.com/haskell-crypto/cryptonite/search?p=1&q=undefined&type=&utf8=%E2%9C%93

**Comment by ocheron** [comment]
Yes but for things like ciphers or hash algorithms this is more delicate: the types are part of exposed API so going from `a` to `Proxy a` is an API change.

**Comment by michalrus** [comment]
I see… :crying_cat_face:
