### ISSUE TITLE
Relation to cryptohash?

### ISSUE THREAD

**Issue by FranklinChen** [haskell-crypto/cryptonite#2]
Maybe there should be a note about the relationship of Cryptonite to CryptoHash https://github.com/vincenthz/hs-cryptohash especially because of overlapping module namespaces?

**Comment by vincenthz** [comment]
I haven't manage to outlines those things yet, but a post is coming really soon about this.

Basically cryptonite is a superset of cryptohash, I plan to maintain cryptohash for longer than other of my crypto packages, but eventually, I don't think anyone should use any other packages anymore now.

Does that answer your question ?

**Comment by FranklinChen** [comment]
Yes, that answers my question. I think the confusing thing right now is the namespace clash, while many packages already use cryptohash. I guess I will plan to use Cryptonite for anything new.
