### ISSUE TITLE
Google Authenticator secret keys

### ISSUE THREAD

**Issue by amitojps** [haskell-crypto/cryptonite#213]
Cryptonite already has functions for creating and verifying one time passwords based on some secret key. I think the `Crypto.OTP` module should also provide a simple way of generating a secret key for apps like Google Authenticator.

**Comment by tekul** [comment]
The key used in OTP is just a byte array which you would generate using `getRandomBytes`. For human consumption, apparently Google Authenticator requires it to be encoded as Base 32, with any `=` padding characters removed. You can convert it to Base32 using the functions in the [memory package](https://hackage.haskell.org/package/memory-0.14.12/docs/Data-ByteArray-Encoding.html).

Is that what you need?

**Comment by tekul** [comment]
No response, so closing, since there isn't really a standard way to provide keys to OTP apps and it isn't too hard to encode generated bytes to hex, base32 or whatever is required.

**Comment by amitojps** [comment]
My apologies, forgot about this. I'm fine with that.
