### ISSUE TITLE
Expose `Digest` and `Crypto.Hash.Types`

### ISSUE THREAD

**Issue by athanclark** [haskell-crypto/cryptonite#22]
It would be nice to create an empty `Digest` value. Is there any way you could expose this, or make Digest a monoid? Thank you for this project :)

**Comment by vincenthz** [comment]
What are you trying to achieve ? Not sure, what an empty Digest is, and I don't think Digest behave like a monoid (e.g. appending 2 `Digest SHA1` doesn't yield a `Digest SHA1`)

**Comment by athanclark** [comment]
That makes a lot of sense actually. My mistake - I'm trying to make a nonce-based session cache in wai-session - found myself using `fromMaybe` and needed a default value. Sorry about that!

**Comment by athanclark** [comment]
I still would like to convert a `Digest` into a `ByteString` - do you have any tips for this? :\

**Comment by vincenthz** [comment]
you can use `Data.ByteArray.convert` from the `memory` package to do that

**Comment by athanclark** [comment]
Ahh! The typeclasses are fooling me! Thank you!
