### ISSUE TITLE
Make "safe" FFI calls to Argon2 (and possibly other KDFs)

### ISSUE THREAD

**Issue by hce** [haskell-crypto/cryptonite#224]
Seems like making an unsafe call to a long-running (several seconds) C function can "DoS" the whole haskell runtime. I suggest to make "safe" FFI calls instead to these functions, to avoid such situations.

**Comment by vincenthz** [comment]
probably providing both (safe and unsafe binding), is a good idea. PR welcome

**Comment by hce** [comment]
I don't understand why you want to provide both. As far as I understand it (I am by no means a haskell FFI binding expert) you have to choose between safe and unsafe. Anything declared "unsafe" means that the C part of the binding has to take care of certain housekeeping (which includes not to block in anyway and to finish as quickly as possible) while anything declared "safe" will get a wrapper from the haskell runtime so the haskell runtime doesn't run into problems even if the called C function blocks, etc.

**Comment by hce** [comment]
Okay, let me investigate this a bit further.

**Comment by vincenthz** [comment]
the time of blocking is more or less directly related to the number of iterations. For example, if you run 1 iteration, then you don't really care if this call is blocking for a tiny amount of time, and the overhead of creating the safe context is much greater than being blocked in unsafe there. Hence why I think exposing both is a good idea.

Edit: I was actually thinking about PBKDF2 here, but the same reason apply to other slow hashing algorithms to a certain extent

**Comment by hce** [comment]
I think I misunderstood what "safe" and "unsafe" means.

Apparently, "safe" simply means that a C function doesn't call back to haskell, but otherwise the C function is not required to return quickly to the haskell runtime. So this issue doesn't make sense, I recommend to close it.
