### ISSUE TITLE
Bcrypt - incorrect cost parsing for 20-30 inclusive

### ISSUE THREAD

**Issue by adituv** [haskell-crypto/cryptonite#230]
Source code takes `10^costTens` where it should be `10*costTens` (and that also eliminates the if statement).  I have checked that it fails to validate a hash of cost 20:

```haskell
main = do
    computedHash <- hashPassword 20 rawPass
    putStrLn (if validatePassword rawPass computedHash
                 then "Validation succeeded"
                 else "Validation failed"
  where
    rawPass = "Hello World" :: ByteString
```

(Output from program with explanatory logging:)
```
Hashing "Hello World" with random salt, cost 20
Hash: $2b$20$xVIy2sbm1Gh.WOXEFHy67.y/RwuSFp9BiomOVuOXA9YSo6dTTaQ1a
Validation failed
```

**Comment by ocheron** [comment]
It looks you're right, and that adding a test vector would be too slow unfortunately.
Do you want to send a PR to fix the issue?

**Comment by tekul** [comment]
I added a fix. Thanks for spotting this!
