### ISSUE TITLE
Cannot access cryptonite documentation

### ISSUE THREAD

**Issue by mouse07410** [haskell-crypto/cryptonite#231]
Browsers complain:
```
Error 503 Connection timed out

Connection timed out
Guru Mediation:

Details: cache-bos8231-BOS 1523583292 3963007562

Varnish cache server
```

Is there an alternative place where I can get the documentation from?

**Comment by NicolasDP** [comment]
Hi @mouse07410 , I think the best place to get `cryptonite` documentation is from stackage : https://www.stackage.org/package/cryptonite

**Comment by mouse07410** [comment]
Indeed that is the best place - and it works. Thank you, Nicolas!
