### ISSUE TITLE
secp256k1 parameters

### ISSUE THREAD

**Issue by ProofOfKeags** [haskell-crypto/cryptonite#233]
I was taking a look and noticed that we don't have curve parameters for secp256k1. I'd like to work on adding that if possible. Would a PR for this addition be welcome? If so, are there any considerations besides what's in the contributing guidelines?

https://en.bitcoin.it/wiki/Secp256k1

**Comment by ocheron** [comment]
Do you refer to something like below or something else?
https://github.com/haskell-crypto/cryptonite/blob/d27d4646278372549e0540797a48ac4b0ecaecd0/Crypto/PubKey/ECC/Types.hs#L282-L291

**Comment by ProofOfKeags** [comment]
This is actually precisely what I mean. I apologize for missing it. Thanks!

**Comment by ProofOfKeags** [comment]
Let me know if there's any other way I can contribute back to this though
