### ISSUE TITLE
failure on arm64

### ISSUE THREAD

**Issue by clinty** [haskell-crypto/cryptonite#234]
```
      1:                                 test-cryptonite: cbits/decaf/ed448goldilocks/decaf.c:1267: cryptonite_decaf_448_point_decode_like_eddsa_and_ignore_cofactor: Assertion `API_NS(point_valid)(p) || ~succ' failed.
```

https://buildd.debian.org/status/fetch.php?pkg=haskell-cryptonite&arch=arm64&ver=0.25-2&stamp=1523959743&raw=0

**Comment by ocheron** [comment]
I don't have what is necessary to reproduce unfortunately.
Can you test adding the architecture to the following line, to enable 64-bit decaf code?
https://github.com/haskell-crypto/cryptonite/blob/ec8366bbd27b58eb221293d4a6b3f75c78c14f92/cryptonite.cabal#L272

**Comment by clinty** [comment]
Builds and tests pass with

`if arch(x86_64) || arch(aarch64)`

on both the decaf and donna

https://buildd.debian.org/status/fetch.php?pkg=haskell-cryptonite&arch=arm64&ver=0.25-3&stamp=1524524651&raw=0

**Comment by ocheron** [comment]
Thanks for testing. I committed the changes.
