### ISSUE TITLE
Signing messages and verifying signatures on Edwards25519?

### ISSUE THREAD

**Issue by kendricktan** [haskell-crypto/cryptonite#237]
I'm currently using some of the low level utils (such as scalarAdd and scalarMult) in Edwards25519 which is great, however I also need to sign and verify messages on it.

I noticed that Edwards25519 doesn't have a sign and verify so I'm borrowing these utils from Ed25519, however upon signing and verifying it always returns false.

I'm using pointMulByCofactor and pointMul on `Edwards25519` which is why I'm converting between that and Ed25519.

Am I doing something wrong?

```Haskell
{-# LANGUAGE OverloadedStrings #-}

import Crypto.ECC.Edwards25519
import Crypto.PubKey.Ed25519
import Crypto.Error
import System.IO.Unsafe
import Data.ByteString

sk = unsafePerformIO scalarGenerate
pk = toPoint sk

(CryptoPassed sk') = secretKey (scalarEncode sk :: ByteString)
(CryptoPassed pk') = publicKey (pointEncode pk :: ByteString)

let msg = "hello" :: ByteString

sig = sign sk' pk' msg

valid = verify pk' msg sig

-- valid is False
```

EDIT: In other words, the question is there anyway to easily to do:
```haskell
Edwards25519.Scalar -> Ed25519.SecretKey
```

**Comment by NicolasDP** [comment]
Hi, to generate a key pair, you can use `Crypto.PubKey.Ed25519.generateSecretKey`, it's defined here: https://www.stackage.org/haddock/nightly-2018-04-30/cryptonite-0.25/Crypto-PubKey-Ed25519.html#v:generateSecretKey 

The curve arithmetic and the signature scheme are slightly different.

**Comment by kendricktan** [comment]
@NicolasDP Thanks for the reply, I understand that you can use Ed25519 to generate a secret key.

But I would like to use low level functions like `pointAdd` and `pointMul` which only exists in `Edwards25519`, as well as `sign` and `verify` which however only exists in `Ed25519`.

So my question is there anyway for me to generate a priv-pub key (scalar and point) in edwards25519 and sign and verify it?

**Comment by kendricktan** [comment]
In other words, is there anyway to easily to do:
```haskell
Edwards25519.Scalar -> Ed25519.SecretKey
```

**Comment by ocheron** [comment]
No this way is not possible. See [RFC 8032 section 5.1.5](https://tools.ietf.org/html/rfc8032#section-5.1.5) and [this implementation](https://gist.github.com/ocheron/892f4b50b7db5f4b3cebedf19d39835c) for the other direction (secret key to scalar, i.e. functions `secretScalar` and `scheduleSecret`). In EdDSA the secret key is not a scalar.

**Comment by kendricktan** [comment]
Awesome! Thanks. I've extended it so it can sign messages with a `Scalar` and verify with a `Point`.

https://gist.github.com/kendricktan/14a4f193d961663c3d002c6fcf50d964#file-ed25519_extended-hs-L94
