### ISSUE TITLE
Make ECIES work with sec_p* curves

### ISSUE THREAD

**Issue by gip** [haskell-crypto/cryptonite#249]
My (limited) understanding is that sec_p* curves could be able to be leveraged by ECIES - that is actually done in some case. At the moment the curves defined in `Crypto/PubKey/ECC/Types.hs` like `SEC_p*` are not an instance of `class EllipticCurve`. Was this a design choice or is there a way to achieve that?

**Comment by gip** [comment]
Actually I now release that this is done for some of them: https://github.com/haskell-crypto/cryptonite/blob/master/Crypto/ECC.hs#L155

Any reason this cannot (or shouldn't) be extended to other curves?

**Comment by ocheron** [comment]
Those already available are the ones used for ECDHE in tls.
It's certainly possible to add a few more that are useful.
Adding all, I'm not so sure. Many other curves are supposed to be deprecated.

**Comment by vincenthz** [comment]
It's possible to add some more as @ocheron mentioned, but I'm not very convinced that everything about k and b curves is correct. It's also much less used than the current curves exposed and generally in the crypto world seem not much used anymore, except from P256K1.
