### ISSUE TITLE
i2osp unsigned or signed output representation

### ISSUE THREAD

**Issue by adamschoenemann** [haskell-crypto/cryptonite#259]
I was recently bitten by some confusion about the behaviour of i2osp -- according to [this answer][1] when converting an integer whose bit-representation has the most-significant bit set, the deserialization of the integer should be prefixed by a null-byte. I've observed that bouncycastle's implementation does this but i2osp in cryptonite does not. 
I'm not quite sure how to read [the spec][2] so I don't know if this can be considered correct or incorrect behaviour, but I think it warrants a note or a comment in the documentation nonetheless.
For reference, here is a working (but probably inefficient) implementation of the behaviour described in the first link.

```haskell
import qualified Data.Bytestring as BS
import qualified Data.Bits as Bits
import Crypto.Number.Serialize (os2ip)

i2ospFixed :: Integer -> ByteString
i2ospFixed i =
  let bs = i2osp i
      msb = BS.head bs
      leftmostBitSet = not (BS.null bs) && Bits.testBit msb 7
  in if leftmostBitSet then BS.cons 0 bs else bs
```

[1]: https://crypto.stackexchange.com/questions/1795/how-can-i-convert-a-der-ecdsa-signature-to-ASN.1
[2]: https://tools.ietf.org/html/rfc3447#page-9

**Comment by vincenthz** [comment]
This has to do with the fact that integer in haskell don't encoded their own size, which is different from a cryptographic Integer of N bits. If you want to serialize your integer to a specific size, for example 1024 bits, then you'll have to use `i2ospOf 128 n` not `i2osp n`. the later would squash all leading bytes that are zero so that the integer `0` is encoded as `"0"` not `"00000000...0000"` like you expect.

**Comment by adamschoenemann** [comment]
I think you misunderstood me, which is probably because I didn't do a very good job of explaining the actual problem. It's not to do with the size of the bytestrean but rather that integers whose bit representation has the "leftmost" bit set is interpreted as negative but i2osp in this case encodes the integer into an unsigned encoding which may be surprising. I'm not saying you're doing it wrong since I can't at first glance see it mentioned in the spec but I hoped to help others in my position by having it mentioned in the documentation :-)

**Comment by ocheron** [comment]
Integers R and S in (EC)DSA signatures are encoded to ASN.1. Indeed this is distinct from what `i2osp` does.

An example with the full ASN.1 libraries is here:
https://github.com/vincenthz/hs-certificate/blob/200f90bf5f4d483ff8213bc67559642ece771c89/x509-validation/Tests/Certificate.hs#L164

**Comment by adamschoenemann** [comment]
Thanks for the link and answer. I guess I confused the two because using i2osp *almost* gives an ASN.1 encoded integer. Anyway, personally I think the documentation could use a small note describing that the integer is serialized as an unsigned integer, but if you don't feel this is appropriate that's fine too :)
