### ISSUE TITLE
How to serialize a signature?

### ISSUE THREAD

**Issue by crockeea** [haskell-crypto/cryptonite#263]
I cannot find an easy way to serialize a signature, for example, from Crypto.PubKey.DSA. This functionality is required, e.g., for creating a self-signed certificate. I need to sign an object and append its (serialized) signature using[ `objectToSignedExactF`](http://hackage.haskell.org/package/x509-1.7.5/docs/Data-X509.html).

**Comment by ocheron** [comment]
For DSA integers R and S are encoded to an ASN.1 container.

You can find some examples here:
https://github.com/vincenthz/hs-certificate/blob/3215720c2b78f936417e0680e23981d475885ba1/x509-validation/Tests/Certificate.hs#L171
and here:
https://github.com/vincenthz/hs-tls/blob/c1cb121334786dd9a5c8fdc4a653e82e94e3822f/core/Network/TLS/Crypto.hs#L276

**Comment by crockeea** [comment]
It feels like this should be part of (some) library, rather than just in the tests. Are you aware of anything that already handles the ASN.1 encoding?

**Comment by tekul** [comment]
The tests are calling [functions in the `asn1-encoding` library](https://hackage.haskell.org/package/asn1-encoding-0.9.5/docs/Data-ASN1-Encoding.html).

**Comment by crockeea** [comment]
I'm referring to the portion that actually creates the list of ASN1 values:

```
DER         [ Start Sequence
                 , IntVal (DSA.sign_r sig)
                 , IntVal (DSA.sign_s sig)
                 , End Sequence]
```
and
`dsaSequence sign = [Start Sequence,IntVal (DSA.sign_r sign),IntVal (DSA.sign_s sign),End Sequence]`

These encodings are standardized, yes?

**Comment by crockeea** [comment]
@ocheron kxSign doesn't support ECDSA.

**Comment by ocheron** [comment]
Yes there's a reason for this.

From Crypto.PubKey.ECC.ECDSA:
> WARNING: Signature operations may leak the private key.

x509-validation test suite has sample code to produce a signature.
