### ISSUE TITLE
Add CRC32 to Hash

### ISSUE THREAD

**Issue by merijn** [haskell-crypto/cryptonite#269]
Given how complete the hash suite in cryptonite is, it's a shame CRC32 is missing, given how widely used it is. I can write an implementation and open a PR, but before I invest the effort I'd prefer to know there's interest in adding it.

**Comment by ocheron** [comment]
I don't think it qualifies as cryptographic hash.

**Comment by merijn** [comment]
I guess not. On the other hand, I think it would be nice to have a nicely complete suite of hashes with cryptonite's API. On the other hand maybe that's a job for a separate library depending on cryptonite using the `HashAlgorithm` class...

OTOH, at this point in time MD4/MD5 are only cryptographic hash in terms of "original design goals", rather than "actual safe use" :)

**Comment by vincenthz** [comment]
sadly yes, agreed with @ocheron, it doesn't fit cryptonite mission despite fitting perfectly its interface.

as for MD4/MD5, they are still cryptographic hash, despite being mostly curiosity code at this stage and can be still be find every now and then in older systems. it's not the policy of cryptonite to enforce the security aspect
