### ISSUE TITLE
Building on Mac OSX 10.8.5, Haskell Platform 2014.2.0.0 fails

### ISSUE THREAD

**Issue by jamescheney** [haskell-crypto/cryptonite#27]
The reason seems to be that the GCC flag -maes is not supported on the stock version of gcc on OSX 10.8.5, namely gcc 4.2.1.  This flag doesn't seem to appear until GCC 5.2, so it would be good to detect the GCC version and add this flag only if -maes is supported.

jcheney$ sudo cabal install cryptonite --verbose
Reading available packages...
Choosing modular solver.
Resolving dependencies...
Ready to install cryptonite-0.5
Extracting
/Users/jcheney/Library/Haskell/repo-cache/hackage.haskell.org/cryptonite/0.5/cryptonite-0.5.tar.gz
to /tmp/cryptonite-0.5-48364...
Waiting for install task to finish...
Updating cryptonite.cabal with the latest revision from the index.
Configuring cryptonite-0.5...
creating /tmp/cryptonite-0.5-48364/cryptonite-0.5/dist/setup
creating /tmp/cryptonite-0.5-48364/cryptonite-0.5/dist
creating /tmp/cryptonite-0.5-48364/cryptonite-0.5/dist/setup
/Users/jcheney/.cabal/setup-exe-cache/setup-Cabal-1.18.1.4-x86_64-osx-ghc-7.8.3
configure --verbose=2 --ghc --prefix=/Users/jcheney/Library/Haskell
--bindir=/Users/jcheney/Library/Haskell/bin
--libdir=/Users/jcheney/Library/Haskell/ghc-7.8.3-x86_64/lib
--libsubdir=cryptonite-0.5 --libexecdir=/Users/jcheney/Library/Haskell/libexec
--datadir=/Users/jcheney/Library/Haskell/share
--datasubdir=ghc-7.8.3-x86_64/cryptonite-0.5
--docdir=/Users/jcheney/Library/Haskell/ghc-7.8.3-x86_64/lib/cryptonite-0.5/doc
--htmldir=/Users/jcheney/Library/Haskell/ghc-7.8.3-x86_64/lib/cryptonite-0.5/doc/html
--haddockdir=/Users/jcheney/Library/Haskell/ghc-7.8.3-x86_64/lib/cryptonite-0.5/doc/html
--sysconfdir=/Users/jcheney/Library/Haskell/etc --enable-library-profiling
--user --flags=-support_pclmuldq --flags=support_deepseq --flags=support_aesni
--flags=integer-gmp --extra-prog-path=/Users/jcheney/Library/Haskell/bin
--constraint=memory ==0.7 --constraint=integer-gmp ==0.5.1.0
--constraint=ghc-prim ==0.3.1.0 --constraint=deepseq ==1.3.0.2
--constraint=bytestring ==0.10.4.0 --constraint=base ==4.7.0.1 --disable-tests
--disable-benchmarks
Redirecting build log to {handle:
/Users/jcheney/.cabal/logs/cryptonite-0.5.log}
Building cryptonite-0.5...
creating /tmp/cryptonite-0.5-48364/cryptonite-0.5/dist/setup
/Users/jcheney/.cabal/setup-exe-cache/setup-Cabal-1.18.1.4-x86_64-osx-ghc-7.8.3
build --verbose=2
Redirecting build log to {handle:
/Users/jcheney/.cabal/logs/cryptonite-0.5.log}
Failed to install cryptonite-0.5
Last 10 lines of the build log ( /Users/jcheney/.cabal/logs/cryptonite-0.5.log ):
[88 of 93] Compiling Crypto.Cipher.Camellia ( Crypto/Cipher/Camellia.hs, dist/build/Crypto/Cipher/Camellia.p_o )
[89 of 93] Compiling Crypto.Cipher.DES ( Crypto/Cipher/DES.hs, dist/build/Crypto/Cipher/DES.p_o )
[90 of 93] Compiling Crypto.Cipher.TripleDES ( Crypto/Cipher/TripleDES.hs, dist/build/Crypto/Cipher/TripleDES.p_o )
[91 of 93] Compiling Crypto.PubKey.ECC.P256 ( Crypto/PubKey/ECC/P256.hs, dist/build/Crypto/PubKey/ECC/P256.p_o )
[92 of 93] Compiling Crypto.PubKey.Ed25519 ( Crypto/PubKey/Ed25519.hs, dist/build/Crypto/PubKey/Ed25519.p_o )
[93 of 93] Compiling Crypto.Cipher.AES ( Crypto/Cipher/AES.hs, dist/build/Crypto/Cipher/AES.p_o )
Building C Sources...
creating dist/build
/usr/bin/ghc -c -odir dist/build -Idist/build/autogen -Idist/build -Icbits -Icbits/ed25519 -optc-mssse3 -optc-maes -optc-DWITH_AESNI -optc-O2 -package-db dist/package.conf.inplace -package-id base-4.7.0.1-df210ede1eb79477fef5662549c32927 -package-id bytestring-0.10.4.0-4aa78c8ca7b6b65993eefc131f7d94fa -package-id deepseq-1.3.0.2-8f63133c1b77f3b3190f04893cf340e4 -package-id ghc-prim-0.3.1.0-954cb57749cf319beafdc89b3415422c -package-id integer-gmp-0.5.1.0-d42e6a7874a019e6a0d1c7305ebc83c4 -package-id memory-0.7-f369ee4f598039d1fc5f4df51fe53651 cbits/cryptonite_chacha.c
cc1: error: unrecognized command line option "-maes"
World file is already up to date.
cabal: Error: some packages failed to install:
cryptonite-0.5 failed during the building phase. The exception was:
ExitFailure 1

**Comment by tekul** [comment]
I think you should be able to run

```
cabal install --flags="-support_aesni"
```

to disable use of aesni instructions.

**Comment by jamescheney** [comment]
Thanks.  That works.  I actually ran into this issue as a result of a MacPorts package trying to install cryptonite, so a fix that means that "cabal install cryptonite" does the right thing out of the box would still be helpful.  I can re-file the above suggestion against that package and see if they can incorporate it into the port file somehow.

**Comment by jamescheney** [comment]
Wait, sorry, never mind - I was thinking of something else!  It would still be helpful for cabal install to automatically detect the need for this flag, so that other cabal install builds that depend on cryptonite will work, but my comment about MacPorts is completely irrelevant...

**Comment by FranklinChen** [comment]
Older discussion was here: https://github.com/haskell-crypto/cryptonite/issues/21
