### ISSUE TITLE
aes-gcm is slower than openssl's

### ISSUE THREAD

**Issue by junjihashimoto** [haskell-crypto/cryptonite#273]
When I use aes with https, hs-tls is twice slower than hsopenssl.
perf-top's output is below.
https://github.com/vincenthz/hs-tls/issues/357

**Comment by vincenthz** [comment]
mostly a known issue due to not using: tables and hardware permitted pclmul/avx

**Comment by ocheron** [comment]
@junjihashimoto Would you try your measurement again, enabling flag `support_pclmuldq` with merged #278 ?

**Comment by junjihashimoto** [comment]
Thanks! I try it.

**Comment by junjihashimoto** [comment]
@ocheron This is great. 

hsopenssl
![image](https://user-images.githubusercontent.com/2469618/58299178-3fbace00-7e19-11e9-9bb0-c624636a75c1.png)

With enabling flag `support_pclmuldq`
![image](https://user-images.githubusercontent.com/2469618/58298839-f918a400-7e17-11e9-9803-467bf7aacf78.png)

Without enabling flag `support_pclmuldq`
![image](https://user-images.githubusercontent.com/2469618/58299974-d7b9b700-7e1b-11e9-9979-1901bcc90d42.png)

cpu usage : timeline is hsopenssl(11:38-11:40), disabling  flag `support_pclmuldq`(11:42-11:46) and enabling flag `support_pclmuldq`(11:58-12:00).

![image](https://user-images.githubusercontent.com/2469618/58300055-1fd8d980-7e1c-11e9-8757-f54ad8c5dbf4.png)

**Comment by ocheron** [comment]
Thanks for confirming. We can probably enable the flag by default like support_aesni in a next release.
Also an optimization with small table is still a good idea when pclmuldq is not possible.
