### ISSUE TITLE
Expose internals of Crypto.Cipher.XSalsa.State

### ISSUE THREAD

**Issue by Shimuuar** [haskell-crypto/cryptonite#279]
I had to reimplement TweetNaCl.js's public key authenticated encryption. They use initialization of XSalsa as key derivation function. Would it be possible to either expose  `Crypto.Cipher.XSalsa.State` constructor or add `ByteArrayAccess` to it? Right now I have to resort to `unsafeCoercing` it which is somewhat questionalble practice

**Comment by ocheron** [comment]
I'm not familiar with that part but it seems the constructor is already available from `Crypto.Cipher.Salsa`.

**Comment by Shimuuar** [comment]
Yes you're right. I somehow missed that. Sorry for the confusion
