### ISSUE TITLE
blowfish key size inconsistency

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell-crypto/cryptonite#282]
I noticed that the `Blowfish` cipher declares a key size of between 6-56 bytes, and the `BlowfishN` variants declare an exact key size, but `cipherInit` accepts any key <= 56 bytes for all of them. Is that intentional?

**Comment by ocheron** [comment]
I think it's there to show a minimum which is not too weak.
Wikipedia mentions a minimum of 32 bits like in the original papers.
Internally blowfish repeats the byte sequence. Encryption result is not changed when appending a small key to itself.
