### ISSUE TITLE
bcrypt is 30x slower running in CircleCI

### ISSUE THREAD

**Issue by mossprescott** [haskell-crypto/cryptonite#285]
I have a function which hashes API keys using `bcrypt 8 salt` where salt is `"<16 ASCII chars>" :: ByteString`. Evaluating it seems to be 30x slower when my tests run in CircleCI, as compared to locally. 

Here's a trivial test which exhibits the behavior:

```haskell
simpleTest :: IO ()
simpleTest = do
  let salt = "0123456789abcdef" :: ByteString
      key = "This is a reasonably long string with only ASCII characters in it for now. \
            \Not sure exactly how long the actual API keys are, but probably not this many bytes." :: ByteString
  void $ timed "bcrypt" $ pure $! (bcrypt 8 salt key :: ByteString)

timed :: (MonadIO m) => Text -> m a -> m a
timed msg ma = do
  start <- getCurrentTime
  result <- ma
  end <- getCurrentTime
  putStrLn $ msg <> ": " <> tshow (end `diffUTCTime` start)
  pure result
```

When I run it locally (on a 2015 MacBook Pro), it takes about 55ms. In CircleCI, it takes 1.6 seconds. Compiling with `-O2` reduces both times somewhat but the disparity remains.

I don't know too much about the CircleCI environment, but it reports this when it starts:
```
Docker Engine Version: 18.09.6
Kernel Version: Linux 5d413d39d998 4.15.0-1035-aws #37-Ubuntu SMP Mon Mar 18 16:15:14 UTC 2019 x86_64 Linux
```
Both are running with `stack test` and the resolver is lts-13.23.

Note: I'm also running this code on hosted web servers (where Servant and several layers of middleware are also involved) and response times are in the 20-100ms range, so I know I don't have the problem there either, so it might be a Docker thing but it's not a virtualization thing, so it would seem.

Looking at the implementation briefly, I don't see any obvious reason why it would run so differently in this one environment. I have my suspicions when I see things like `indexWord32Array#`, but no actual knowledge of what complexities they might create for the compiler.

Any help is appreciated.

**Comment by ocheron** [comment]
Could you test if cryptonite-0.26 exhibits same behavior?
Compared to cryptonite-0.25 the implementation changed significantly.

**Comment by mossprescott** [comment]
Interesting! Added `cryptonite-0.26` to `extra-deps` in stack.yaml.

Locally: 32ms with 0.26 (down from 52ms in my most recent runs; 38% faster).
CircleCI: 70ms with 0.26 (down from 1.6s; pretty much _all_ of the %s faster)!!!

@ocheron is now my personal hero.

**Comment by ocheron** [comment]
All credit goes to @lpeterse.
