### ISSUE TITLE
Hashable instances for Crypto.Hash.Digest?

### ISSUE THREAD

**Issue by moll** [haskell-crypto/cryptonite#289]
Hey,

First, thanks for maintaining Cryptonite! Second, is there a reason `Crypto.Hash.Digest` lacks an `Hashable` instance for them to be used as keys in a `Data.HashMap`? They do have an `Ord` instance, so I presume the use case of mapping them was already thought of.

Thanks!

**Comment by vincenthz** [comment]
There's no technical reason, just an extra dependency reason for hashable and its transitive dependencies (specially text). The way to solve this problem is to newtype it (hint below) or more elaborate add support instance for `basement`'s `Hash` and make a basement friendly HashMap:

```newtype D = D (Digest ..)

instance Hash D for ...
    ....
```

**Comment by moll** [comment]
Thanks! The extra dependency argument is always convincing, though I thought `Hashable` comes with GHC...
