### ISSUE TITLE
Testsuite failure: generate-param: FAIL

### ISSUE THREAD

**Issue by nomeata** [haskell-crypto/cryptonite#29]
I have seen this test failure:

```
    generate-param:          FAIL
      *** Failed! Falsifiable (after 72 tests): 
      TestDRG (10131262950327,4047807192587,4049022727728,12263005592284,10034241927390)
      Int0_2901 0
      Use --quickcheck-replay '71 TFGenR 2A35C0FFB673D1548CEF319A5BE591B6F8C90A7F3E3B4BAE04D9E9CF8A07B9C4 0 1023 10 0' to reproduce.
```

e.g. [here](https://buildd.debian.org/status/fetch.php?pkg=haskell-cryptonite&arch=kfreebsd-amd64&ver=0.6-2&stamp=1440558379) and similarly [here](https://buildd.debian.org/status/fetch.php?pkg=haskell-cryptonite&arch=armhf&ver=0.6-2&stamp=1440559317). 

As these are quite different architectures it is likely that this is an architecture-independent bug.

**Comment by vincenthz** [comment]
dup of #28
