### ISSUE TITLE
Crypto.KDF.Scrypt's [generate] differs from Crypto.Scrypt's [encryptPass]

### ISSUE THREAD

**Issue by Vlix** [haskell-crypto/cryptonite#308]
I've tried to make the same function as the one in [`scrypt`](https://hackage.haskell.org/package/scrypt-0.5.0/docs/Crypto-Scrypt.html)'s `encryptPass`, but using [`cryptonite`](https://hackage.haskell.org/package/cryptonite-0.26/docs/Crypto-KDF-Scrypt.html)'s `generate` function.

Turns out, they both create different hashes, given the same parameters... so which one is correct?

```
"16|8|1|iQ6jG1QiHdC57HOBK6TXYN3DOkqjbF/lR+6U4jlPGvI=|NqLTuI6Aj/OqN24Bes9kpAxcoqwZ614JrnnNzYcSCZkyEovP5dsc0Q754saNmV0kpbMtXsxNR5mxq8B44Qwwsw=="
"16|8|1|iQ6jG1QiHdC57HOBK6TXYN3DOkqjbF/lR+6U4jlPGvI=|o2/UjX07yH1q4YmepP0eBBdzaaP5Fk6C8M9gKLun2jSysuqIK6I4GG7fIVxBZ+6SI67eXeoXqPQvEyJnEcp79A=="
```

**Comment by ocheron** [comment]
Did you try running the test suites?
Both packages include test vectors from https://tools.ietf.org/html/rfc7914#section-12.

Beware format of parameter N is not the same in cryptonite and scrypt.

**Comment by Vlix** [comment]
Ah, you might be right. `Crypto.KDF.Scrypt`'s `N` is the actual cost, instead of `2^N`. Will try again and report.

**Comment by Vlix** [comment]
You were right, the hashes match, thanks.
