### ISSUE TITLE
Improve documentation for SHAKE

### ISSUE THREAD

**Issue by schmittlauch** [haskell-crypto/cryptonite#313]
Disclaimer: I'm relatively new to Haskell.

When working with the `hash` function to create SHAKE128 or SHAKE256 digests, it wasn't clear to me that the SHAKE128 type required the DataKinds GHC extension. I only found out about this thanks to the examples in #131.

I suggest adding an example for working with such parameterisable digests to the Crypto.Hash docs and/or to the Crypto.Tutorial.

I'm willing to do the work but would like to have feedback on where to do this best first. Also, I haven't managed to get `hashWith` working with SHAKE128 and need a working example for that.

**Comment by ocheron** [comment]
An example is welcome in Crypto.Hash or the tutorial.
hashWith is like any other hash algorithm but with an argument like `(SHAKE128 :: SHAKE128 256)`.
