### ISSUE TITLE
public key -> ASN.1 DER encoded entity 

### ISSUE THREAD

**Issue by GildedHonour** [haskell-crypto/cryptonite#320]
Given a public Rsa key, how can I decode  ASN.1 DER encoded entity in it?

In Elixir it'd be 

```
pub_key = "something"
1) Base.decode64!
2) s1 = get_substr_from_26th_byte_til_end
3) :public_key.der_decode(:RSAPrivateKey, <<s1>>)
```

In this library I haven't found anything similar to the 3rd step.

https://erlang.org/doc/man/public_key.html#der_decode-2

**Comment by GildedHonour** [comment]
Is there such a function?

**Comment by vincenthz** [comment]
Have a look at :
https://github.com/vincenthz/hs-certificate/blob/master/x509-util/src/Certificate.hs

all the ASN.1 are not available in this package, but through the asn1-encode and certificate packages.
