### ISSUE TITLE
Segfault when running compiled with optimization: 0

### ISSUE THREAD

**Issue by sordina** [haskell-crypto/cryptonite#334]
I'll try to create a minimal reproduction, but I'll first create an issue in case this is known.

When building with

* Darwin difference.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 18 20:50:10 PDT 2020; root:xnu-4903.278.43~1/RELEASE_X86_64 x86_64
* GHC 8.10.2
* cabal-install version 3.2.0.0, compiled using version 3.2.0.0 of the Cabal library
* cabal.project.local:  package * `optimization: 0`

My application (and ghcide) crash with segfaults. Examining the core-dump I've found that cryptonite is where the fault is triggered:

```
Thread 14 Crashed:
0   graphql-websockets    	0x000000010ca2954f gfmul_generic + 47
1   graphql-websockets    	0x000000010ca20e47 ghash_add + 71
2   graphql-websockets    	0x000000010ca26918 cryptonite_aesni_gcm_encrypt256 + 2648
3   graphql-websockets    	0x000000010ca36a80 cryptonite_aes_gcm_encrypt + 96
4   graphql-websockets    	0x000000010c9fca25 Lc2p3M_info + 197
```

I found this issue running a websockets connection with `runClient` from: https://hackage.haskell.org/package/websockets-0.12.7.1/docs/Network-WebSockets-Client.html

It's very possible that this isn't directly a cryptonite issue, but I thought I'd create an issue here to keep track of narrowing down the root-cause. Please let me know if you think it isn't valid and I'll happily move the issue elsewhere!

**Comment by sordina** [comment]
Simple reproduction is proving harder than anticipated.

**Comment by robx** [comment]
Oh seems this is the bug I've been tracing. My environment:

- Darwin ed 18.7.0 Darwin Kernel Version 18.7.0: Tue Jun 22 19:37:08 PDT 2021; root:xnu-4903.278.70~1/RELEASE_X86_64 x86_64
- GHC versions 8.10.2, 8.10.4, 8.10.7 all fail
- cryptonite 0.28, 0.29, current master

Then, the following segfaults with the same stack trace.

```
$ cabal run -O0 test-cryptonite -- -p AE1
```
