### ISSUE TITLE
What is the difference between ECC.P256 and ECC.ECDSA?

### ISSUE THREAD

**Issue by yaitskov** [haskell-crypto/cryptonite#336]
I am doing ECC signature verification and rewrite a Java solution for WebAuthn.

As for now it not working and I am debugging.
I am not sure about module. 

Crypto.PubKey.ECC.P256 and Crypto.PubKey.ECC.ECDSA both define Point type.
I lean to P256, but there is no verify function. Point type from P256 is not compatible with verify function from ECDSA. Meanwhile P256.Point looks more advanced (real type vs just an alias).

So what is the point for existence of Point inside P256?
Where is the function for verifying P256 signatures signatures?

**Comment by nomeata** [comment]
Similarly, I am confused about the relation between `Crypto.PubKey.ECDSA` and `Crypto.PubKey.ECC.ECDSA`…

**Comment by vincenthz** [comment]
@yaitskov `Crypto.PubKey.ECC.ECDSA` only have the support of the pure Haskell implementation (backed by GMP operations), `Crypto.PubKey.ECC.P256` implement a Haskell interface to google `p256.c` implementation. If you want to use P256 with a high level interface use `Crypto.PubKey.ECDSA`

@nomeata along with the explanation above, `Crypto.PubKey.ECDSA` implements a more abstract / typed interface where the type of curve is now a parameter, and thus allow different backend for the actual implementation (in this case it dispatch between pure implementation and p256).

**Comment by nomeata** [comment]
Thanks! Is there a technical reason why `Crypto.PubKey.ECDSA` doesn’t have types for all the curves listed in `Crypto.PubKey.ECC.Types`?

**Comment by vincenthz** [comment]
IIRC it's mostly due to exposing useful curses and not the whole crazy set (some of them vary in the level of insecurity ...)
