### ISSUE TITLE
Write permission

### ISSUE THREAD

**Issue by kazu-yamamoto** [haskell-crypto/cryptonite#377]
@tekul @centromere Could you give me at least "Write" permission for `cryptonite`?
@vincenthz does not respond to my request for a long time.
I would like to release a new version of `cryptonite`.

**Comment by centromere** [comment]
I do not have permission to do so.

**Comment by tekul** [comment]
Me neither. I've pinged Vincent on all the channels I have for him to ask him.

**Comment by kazu-yamamoto** [comment]
@centromere @tekul Thank you for your kindness!

**Comment by kazu-yamamoto** [comment]
I sent an e-mail message to Vincent and he replied.
The answer is "no".
He don't want to give further permissions to anybody and suggested to create a fork.
