### ISSUE TITLE
Can't implement hash functions

### ISSUE THREAD

**Issue by centromere** [haskell-crypto/cryptonite#44]
I'd like to use the HMAC functionality of cryptonite with an unsupported hash function (BLAKE2b/s), but I am unable to do so because the HashAlgorithm class is not exported.

**Comment by vincenthz** [comment]
I'ld like to think it's by design, so that someone would contribute the BLAKE2s/b implementation :)

There should be almost everything needed to generate the haskell bits, (in the `gen` directory), so it's "just" missing the C implementation in cbits/

**Comment by centromere** [comment]
The entries in Gen.hs look like this:

```
, GenHashModule "SHA512"    "sha512.h"    "sha512"    256 64 128 []
```

BLAKE2 has a variable output length. What's the best way to proceed?

**Comment by vincenthz** [comment]
I haven't look at the specific, but I would assume just like `SHA3` or `Skein` that have variable output length, the best is to specialize it to whichever length are commonly used.

**Comment by centromere** [comment]
This is no longer relevant to me.
