### ISSUE TITLE
Show instance for CryptoFailable is wrong

### ISSUE THREAD

**Issue by glguy** [haskell-crypto/cryptonite#50]
CryptoFailable has a manually written Show instance that neither surrounds itself or its argument with parentheses correctly. I think that the correct solution is to just derive the correct instance, but for some reason the incorrect one is manually written.

I'll be happy to provide a patch if desired manually implementing the correct instance or deriving the Show instance if that would be helpful; I just need to know which you'd want.

**Comment by vincenthz** [comment]
I don't have strong feelings about this, but why do you say it's wrong ? the `Show` typeclass doesn't have any properties that I know of, about the string that is returned.

**Comment by crockeea** [comment]
I'm only aware of this: https://ghc.haskell.org/trac/ghc/ticket/11628

**Comment by vincenthz** [comment]
@glguy no follow up ?

**Comment by glguy** [comment]
The show type class should make use of the precedence information so that it when other types use the show instance with a precedence argument that things make sense. For example if a type is wrapped in Maybe, it will be responsible for putting parenthesis around itself if that's appropriate.

I'm happy to submit a PR as I mentioned, but I didn't get the impression that you were interested.

An example is

```
Prelude Crypto.Error> Just (CryptoPassed ())
Just CryptoPassed ()
```

The outer parentheses are missing because CryptoFailable didn't add them even though showsPrec was called with precedence 11

Similarly the Show instance is responsible for passing the correct precedence to its fields

```
Prelude Crypto.Error> CryptoPassed (Just ())
CryptoPassed Just ()
```

**Comment by tekul** [comment]
I'm kind of curious why this is a requirement - is there a reference somewhere that says how `Show` should behave? Could you elaborate on why this is important, and what kind of problem it solves, just to expand my general Haskell knowlege?

**Comment by glguy** [comment]
The precedence field allows Show instances to communicate context to each other. It sets the precedence of the context that a shown value is going to be contained in so that that value and produce a string suitable for inclusion in the larger shown value. As long as all the Show instances respect these precedences it makes sense to parametrically include one Show instance inside of another.

By following the meaning of the precedence field that derived Show instances use, this Show instance will be useful in conjunction with the existing ones.

In a case like this where no custom rendering is being done, the derived instance is the easiest way to get an implementation of Show that is well suited to being used with other instances.

**Comment by vincenthz** [comment]
I'm inclined to just merge it, as I can see a mild advantage when printing the value and wanting to copy paste the value back to haskell code, but FYI you haven't explain why you'ld need the Show instance to, effectively, parse properly.

**Comment by glguy** [comment]
I want to be able to use tools like pretty-show to parse the output. I want
the output to be easy to read without constructors flowing into each other.
I think we're spending a lot of time on a simple fix.

**Comment by vincenthz** [comment]
well, we would have spend less time on it, if you're stated the practical reason to do that from the beginning (in place of qualifier like "wrong"), instead of assuming we would be on the same page about Show instance (In my case I'ld rarely have a CryptoFailable nested in anything, or pretty printed).
