### ISSUE TITLE
cryptonite-0.9 fails to build on i586

### ISSUE THREAD

**Issue by mimi1vx** [haskell-crypto/cryptonite#54]
from build log:

  149s] [99 of 99] Compiling Crypto.Cipher.AES ( Crypto/Cipher/AES.hs, dist/build/Crypto/Cipher/AES.p_o )
[  185s] 
[  185s] In file included from cbits/blake2/blake2s.c:21:0: 
[  185s] 
[  185s] cbits/blake2/blake2-config.h:68:2:
[  185s]      error: #error "This code requires at least SSE2."
[  185s]      #error "This code requires at least SSE2."
[  185s]       ^
[  185s] 
[  185s] In file included from cbits/blake2/blake2s.c:24:0: 
[  185s] 
[  185s] /usr/lib/gcc/i586-suse-linux/4.8/include/emmintrin.h:31:3:
[  185s]      error: #error "SSE2 instruction set not enabled"
[  185s]      # error "SSE2 instruction set not enabled"
[  185s]        ^
[  185s] cbits/blake2/blake2s.c: In function ‘blake2s_compress’:
[  185s] 
[  185s] cbits/blake2/blake2s.c:242:3:
[  185s]      error: unknown type name ‘__m128i’
[  185s]        __m128i row1, row2, row3, row4;
[  185s]        ^
[  185s] 
[  185s] cbits/blake2/blake2s.c:243:3:
[  185s]      error: unknown type name ‘__m128i’
[  185s]        __m128i buf1, buf2, buf3, buf4;
[  185s]        ^
[  185s] 
[  185s] cbits/blake2/blake2s.c:250:3:
[  185s]      error: unknown type name ‘__m128i’
[  185s]        __m128i ff0, ff1;
[  185s]        ^
[  185s] 
[  185s] cbits/blake2/blake2s.c:278:3:
[  185s]      warning: implicit declaration of function ‘_mm_loadu_si128’ [-Wimplicit-function-declaration]
[  185s]        row1 = ff0 = LOADU( &amp;S-&gt;h[0] );
[  185s]        ^
[  185s] 
[  185s] cbits/blake2/blake2s.c:278:3:  error: unknown type name ‘__m128i’
[  185s] 
[  185s] cbits/blake2/blake2s.c:279:3:
[  185s]      error: unknown type name ‘__m128i’
[  185s]        row2 = ff1 = LOADU( &amp;S-&gt;h[4] );
[  185s]        ^
[  185s] 
[  185s] cbits/blake2/blake2s.c:280:3:
[  185s]      warning: implicit declaration of function ‘_mm_setr_epi32’ [-Wimplicit-function-declaration]
[  185s]        row3 = _mm_setr_epi32( 0x6A09E667, 0xBB67AE85, 0x3C6EF372, 0xA54FF53A );
[  185s]        ^
[  185s] 
[  185s] cbits/blake2/blake2s.c:281:3:
[  185s]      warning: implicit declaration of function ‘_mm_xor_si128’ [-Wimplicit-function-declaration]
[  185s]        row4 = _mm_xor_si128( _mm_setr_epi32( 0x510E527F, 0x9B05688C, 0x1F83D9AB, 0x5BE0CD19 ), LOADU( &amp;S-&gt;t[0] ) );
[  185s]        ^
[  185s] 
[  185s] cbits/blake2/blake2s.c:281:3:  error: unknown type name ‘__m128i’
[  185s] 
[  185s] cbits/blake2/blake2s.c:282:3:
[  185s]      warning: implicit declaration of function ‘_mm_set_epi32’ [-Wimplicit-function-declaration]
[  185s]        ROUND( 0 );
[  185s]        ^
[  185s] 
[  185s] cbits/blake2/blake2s.c:282:3:
[  185s]      warning: implicit declaration of function ‘_mm_add_epi32’ [-Wimplicit-function-declaration]
[  185s] 
[  185s] cbits/blake2/blake2s.c:282:3:
[  185s]      warning: implicit declaration of function ‘_mm_srli_epi32’ [-Wimplicit-function-declaration]
[  185s] 
[  185s] cbits/blake2/blake2s.c:282:3:
[  185s]      warning: implicit declaration of function ‘_mm_slli_epi32’ [-Wimplicit-function-declaration]
[  185s] 
[  185s] cbits/blake2/blake2s.c:282:3:
[  185s]      warning: implicit declaration of function ‘_mm_shuffle_epi32’ [-Wimplicit-function-declaration]
[  185s] 
[  185s] cbits/blake2/blake2s.c:282:3:
[  185s]      warning: implicit declaration of function ‘_MM_SHUFFLE’ [-Wimplicit-function-declaration]
[  185s] 
[  185s] cbits/blake2/blake2s.c:292:3:
[  185s]      warning: implicit declaration of function ‘_mm_storeu_si128’ [-Wimplicit-function-declaration]
[  185s]        STOREU( &amp;S-&gt;h[0], _mm_xor_si128( ff0, _mm_xor_si128( row1, row3 ) ) );
[  185s]        ^
[  185s] 
[  185s] In file included from cbits/blake2/blake2s.c:38:0: 
[  185s] 
[  185s] cbits/blake2/blake2s-round.h:18:39:
[  185s]      error: ‘__m128i’ undeclared (first use in this function)
[  185s]      #define STOREU(p,r) _mm_storeu_si128((__m128i *)(p), r)
[  185s]                                            ^
[  185s] 
[  185s] cbits/blake2/blake2s.c:292:3:
[  185s]      note: in expansion of macro ‘STOREU’
[  185s]        STOREU( &amp;S-&gt;h[0], _mm_xor_si128( ff0, _mm_xor_si128( row1, row3 ) ) );
[  185s]        ^
[  185s] 
[  185s] cbits/blake2/blake2s-round.h:18:39:
[  185s]      note: each undeclared identifier is reported only once for each function it appears in
[  185s]      #define STOREU(p,r) _mm_storeu_si128((__m128i *)(p), r)
[  185s]                                            ^
[  185s] 
[  185s] cbits/blake2/blake2s.c:292:3:
[  185s]      note: in expansion of macro ‘STOREU’
[  185s]        STOREU( &amp;S-&gt;h[0], _mm_xor_si128( ff0, _mm_xor_si128( row1, row3 ) ) );
[  185s]        ^
[  185s] 
[  185s] cbits/blake2/blake2s-round.h:18:48:
[  185s]      error: expected expression before ‘)’ token
[  185s]      #define STOREU(p,r) _mm_storeu_si128((__m128i *)(p), r)
[  185s]                                                     ^
[  185s] 
[  185s] cbits/blake2/blake2s.c:292:3:
[  185s]      note: in expansion of macro ‘STOREU’
[  185s]        STOREU( &amp;S-&gt;h[0], _mm_xor_si128( ff0, _mm_xor_si128( row1, row3 ) ) );
[  185s]        ^
[  185s] 
[  185s] cbits/blake2/blake2s-round.h:18:48:
[  185s]      error: expected expression before ‘)’ token
[  185s]      #define STOREU(p,r) _mm_storeu_si128((__m128i *)(p), r)
[  185s]                                                     ^
[  185s] 
[  185s] cbits/blake2/blake2s.c:293:3:
[  185s]      note: in expansion of macro ‘STOREU’
[  185s]        STOREU( &amp;S-&gt;h[4], _mm_xor_si128( ff1, _mm_xor_si128( row2, row4 ) ) );
[  185s]        ^
[  185s] error: Bad exit status from /var/tmp/rpm-tmp.QzVuvW (%build)

**Comment by centromere** [comment]
See #55.

**Comment by vincenthz** [comment]
now fixed
