### ISSUE TITLE
build failed on ppc/ppc64/ppc64le/aarch64

### ISSUE THREAD

**Issue by mimi1vx** [haskell-crypto/cryptonite#55]
112s] [99 of 99] Compiling Crypto.Cipher.AES ( Crypto/Cipher/AES.hs, dist/build/Crypto/Cipher/AES.p_o )
[  139s] 
[  139s] In file included from cbits/blake2/blake2s.c:21:0: 
[  139s] 
[  139s] cbits/blake2/blake2-config.h:68:2:
[  139s]      error: #error "This code requires at least SSE2."
[  139s]      #error "This code requires at least SSE2."
[  139s]       ^
[  139s] 
[  139s] cbits/blake2/blake2s.c:24:23:
[  139s]      fatal error: emmintrin.h: No such file or directory
[  139s] compilation terminated.

**Comment by centromere** [comment]
@mimi1vx Does the `blake2-fix` branch build for you?

**Comment by mimi1vx** [comment]
@centromere with blake2-fix works without any observable problems .. see https://build.opensuse.org/package/show/devel:languages:haskell:lts/ghc-cryptonite

**Comment by centromere** [comment]
@katsuyas @mpietrzak Does the `blake2-fix` branch work in your environment? No flags should need to be specified.

**Comment by mimi1vx** [comment]
@centromere for openSUSE packaging must be disabled AESNI and sse-4.1 +rdrnad :(

**Comment by mpietrzak** [comment]
It does compile, I'm not sure yet if it works.
Is there an easy way to check if it works? I'm compiling tests now, but it takes a long time.

btw I'm using https://www.scaleway.com/

**Comment by centromere** [comment]
@mimi1vx Ah, my statement was unclear. I meant to say, `support_blake2_sse` should be disabled by default, so you shouldn't need to specify it one way or the other.

**Comment by bgamari** [comment]
I am also seeing this on ARM. The `blake2-fix` branch appears to build without any trouble.

**Comment by centromere** [comment]
@vincenthz For your consideration. ^

**Comment by wamserma** [comment]
Same as @bgamari - ARM does not have SSE2. cryptonite happens to be in the dependency tree of hakyll, so having this build break is very annoying. Having the fix on hackage so i can just cabal update would be very appreciated as a Christmas present. :)

**Comment by centromere** [comment]
@wamserma According to others, the above fix seems to be working. I can merge it to master, but only @vincenthz can push to hackage.

**Comment by wamserma** [comment]
@centromere I'm fine with waiting until @vincenthz has pushed. There are more important things these days :)

**Comment by vincenthz** [comment]
now fixed
