### ISSUE TITLE
When do I have to use NOINLINE?

### ISSUE THREAD

**Issue by tekul** [haskell-crypto/cryptonite#57]
A lot of the library functions which use "unsafe" functions like `allocAndFreeze` are tagged with the `NOINLINE` pragma.  Is this a requirement? Are there general rules we can follow to know when this is required or not?

The [ghc docs](https://downloads.haskell.org/~ghc/7.10.2/docs/html/users_guide/pragmas.html) aren't very helpful here, indicating that this should never be needed "unless you're very cautious about code size", but I'm guessing that's not the reason in this case. Reading things like [this wiki entry](https://wiki.haskell.org/IO_inside#inlinePerformIO) just confirm that it seems to be one of those "black art" areas of Haskell which are hard to find out more about :-).

**Comment by vincenthz** [comment]
I certainly wish this part of haskell would be extremely thoroughly documented, as most of the time it's needed to use those unsafe IO tricks, but sadly it's not, and somehow reference as black magic indeed.

I think the usual reason in this case, is to not have the code evaluated more than once by an overzealous inliner (the code could be repeated multiples times). Usually though, it shouldn't make any difference for how we use it anyway, as the overall usage is supposed to be referentially transparent, so if the action is done twice, it would give the same result anyway. hopefully we don't have any code that `launchMissile`, and need to be performed strictly once ;-)

**Comment by tekul** [comment]
Thanks Vincent. I understand that duplicating a buffer allocation for the same value shouldn't matter, if it isn't subsequenly changed. However, the bit that stuck out from that second link was

> However things like allocating new buffers should not be done inside inlinePerformIO since that can easily be floated out and performed just once for the whole program, so you end up with many things sharing the same buffer, which would be bad. 

This is obviously much worse. But I don't really understand how the "floating out" by the inliner would happen, or if that's even correct?

So how do you decide when to add the NOINLINE to code? Is it mostly just a precaution? I noticed that some of the functions in the "memory" package which use `unsafeCreate` don't have it, for example, such as those in the [`Data.ByteArray.Mapping`](hackage.haskell.org/package/memory-0.10/docs/src/Data-ByteArray-Mapping.html) module.

**Comment by vincenthz** [comment]
`inlinePerformIO` is somewhat a much different and scarier beast. I think the floating-out that it is referred to, is something like:

```
callFunctionThatAllocate = inlinePerformIO $ create 10 $ \buf -> do something buf

func = do
    callFunctionThatAllocate ..
    callFunctionThatAllocate ..
```

Could be turn into:

```
func = inlineIO $ create 10 $ \buf -> do
     something buf
     something buf
```

which has obviously bad consequences.

For the missing NOINLINE, it could be just stuff I forgot to add. I don't think we need it in any of our cases, as we don't use `inlinePerformIO`, and all our use don't have any observable side-effects (apart from allocating+mutating the memory)

edit: Although `memory` is a general purpose library, so one could be using 'unsafe' functions, with side-effects and things. only the usage in `cryptonite` fall in the case where we're using it fairly safe.

**Comment by tekul** [comment]
Thanks Vincent. I think that clears it up enough.
