### ISSUE TITLE
Is it possible to run with ghci or "cabal repl"

### ISSUE THREAD

**Issue by tekul** [haskell-crypto/cryptonite#58]
During development I'd like to be able to load a module in ghci and mess with the functions, but I've never been able to find a configuration that works (I'm using OSX). For example, trying to load the main library with `cabal repl` I get:

```
$ cabal repl cryptonite
Preprocessing library cryptonite-0.10...
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
ghc: panic! (the 'impossible' happened)
  (GHC version 7.10.2 for x86_64-apple-darwin):
    Loading temp shared object failed: dlopen(/var/folders/v9/36dyvmvd37vg__0jd5rlbyx80000gn/T/ghc2471_0/libghc_7.dylib, 5): Symbol not found: _cryptonite_aesni_decrypt_block128
  Referenced from: /var/folders/v9/36dyvmvd37vg__0jd5rlbyx80000gn/T/ghc2471_0/libghc_7.dylib
  Expected in: flat namespace
 in /var/folders/v9/36dyvmvd37vg__0jd5rlbyx80000gn/T/ghc2471_0/libghc_7.dylib

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
```

Running `cabal repl test-cryptonite`  works OK, but I'd like to be able to use ghci to run library functions directly, rather than via a test suite.

Has anyone been able to do this?

**Comment by vincenthz** [comment]
not sure what the deal is here, and if windows/linux has the same issue.

**Comment by tekul** [comment]
Does it work OK for you?

**Comment by centromere** [comment]
It has never worked for me, but the error is different:

```
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
ghc: panic! (the 'impossible' happened)
  (GHC version 7.10.3 for x86_64-unknown-linux):
    Loading temp shared object failed: /tmp/ghc17386_0/libghc_13.so: undefined symbol: cryptonite_aesni_decrypt_cbc256

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
```

**Comment by tekul** [comment]
I noticed there are quite a few issues open in GHC with similar errors, but I don't know the root cause here. It'd be nice to get it working or find out what the problem is, since I find working with the REPL is a lot more productive than rebuilding and running tests each time I make a change.

**Comment by vincenthz** [comment]
I workarounded the cabal bug so that the aes files are linked in the right order. you still need to run:

```
cabal repl --ghc-option=-fobject-code
```

for everything to work, as there is unsupported unboxed tuples in Crypto.Number.Compat.
