### ISSUE TITLE
truncation support for DSA signature verification

### ISSUE THREAD

**Issue by clinty** [haskell-crypto/cryptonite#61]
I'm using the function below for DSA signature verification; it would be nice if cryptonite could handle this case in some way.

```
+truncatingVerify :: (ByteArrayAccess msg, CHI.HashAlgorithm hash) => hash -> DSA.PublicKey -> DSA.Signature -> msg -> Bool
+truncatingVerify hashAlg pk (DSA.Signature r s) m
+    -- Reject the signature if either 0 < r < q or 0 < s < q is not satisfied.
+    | r <= 0 || r >= q || s <= 0 || s >= q = False
+    | otherwise                            = v == r
+    where (DSA.Params p g q) = DSA.public_params pk
+          y       = DSA.public_y pk
+          hm      = os2ip . dsaTruncate . BA.convert $ hashWith hashAlg m
+
+          w       = fromJust $ inverse s q
+          u1      = (hm*w) `mod` q
+          u2      = (r*w) `mod` q
+          v       = ((expFast g u1 p) * (expFast y u2 p)) `mod` p `mod` q
+          dsaTruncate bs = let lbs = BL.fromStrict bs in if countBits lbs > dsaQLen then B.take (fromIntegral dsaQLen `div` 8) bs else bs -- FIXME: uneven bits
+          dsaQLen = countBits . integerToBEBS $ q
```

**Comment by clinty** [comment]
sorry for the markdown failure; this is just the stock DSA verify function with `dsaTruncate` run on the digest

**Comment by vincenthz** [comment]
Could you explain why you need this or why this shouldn't the default ? Otherwise, I think it looks fine, just make it a PR, and add some documentation, specially outlining why it's different/needed from `verify`.

**Comment by clinty** [comment]
I need it because it's required by RFC4880 (also supposedly FIPS 186-4 though I have not confirmed this).  I don't have any reason that it shouldn't be the default other than the fact that it isn't now.
