### ISSUE TITLE
Ord and Hashable instances for pkey types

### ISSUE THREAD

**Issue by clinty** [haskell-crypto/cryptonite#65]
Please add Ord and Hashable instances for PublicKey and PrivateKey ytpes

**Comment by vincenthz** [comment]
I can't find the other instance of the similar issue for linking, but `Ord` instance for Private key are a bad idea; it's difficult to provide a timing independant version of Ord, and I don't think it make sense to Order the private key set. For `Hashable`, it might be the same timing issue (namely hash function are not specificied to be timing independant), but the main issue for me is adding dependencies to cryptonite.

**Comment by vincenthz** [comment]
https://github.com/vincenthz/hs-crypto-pubkey-types/pull/3

**Comment by clinty** [comment]
Hmm, okay.  I guess I'll have to keep using newtype wrappers.
