### ISSUE TITLE
Make numeric algorithm properties (e.g. hashDigestSize) type-level nats. 

### ISSUE THREAD

**Issue by Ericson2314** [haskell-crypto/cryptonite#71]
The `undefined` trick is fine for internal code, feels but a little sketchy for user code. This also guarantees they are constants, and potentially opens the doors for compile-time-sized arrays etc.

**Comment by vincenthz** [comment]
There's nothing I would like more than to move to Proxy and more type level stuff, but cryptonite still supports 7.0 onwards, and some API predates many of the type level capabilities, and breaking the API there is just not going to happen.

**Comment by Ericson2314** [comment]
Ah gotcha, I came from deprecated https://hackage.haskell.org/package/cryptohash, and just kinda assumed this was therefore a rethink/API in flux.
