### ISSUE TITLE
Cryptonite and bytes

### ISSUE THREAD

**Issue by Ericson2314** [haskell-crypto/cryptonite#73]
Instead of using an explicit mutable context, and using IO, one can also hide everything in this Monad. I doubt this is better in all cases, but it might be more convenient in some. https://github.com/ekmett/bytes/issues/25

**Comment by vincenthz** [comment]
bytes doesn't support any of the ByteArrayAccess / ByteArray classes (from `memory`). Also in some places I need to have exact control on how things are represented/copied for security reason, for example HMAC where the hash need to be done in a specific fashion so as not to have additional copy of your key in memory.

**Comment by Ericson2314** [comment]
To be clear, I was thinking an additional interface, not replacing the `memory` classes. Also, while that issue mentioned encryption and hashing, I was thinking mostly about that latter. Specifically, I think https://hackage.haskell.org/package/cryptonite-0.13/docs/Crypto-Hash-IO.html#t:HashAlgorithm is powerful enough for

``` haskell
instance HashAlgorithm h => MonadPut (Hash h) where
  -- ...
```

There is no `HashAlgorithm a => HashAlgorithm (HMAC a)` instance, so I am less concerned, but what exactly is the problem here? I'd assume a similarly constructed `HMACMonad` would have to be eliminated with a key, something like:

``` haskell
runHMACMonad :: (HashAlgorithm a, ByteArrayAccess key) => HMACMonad a -> key -> Digest a
```
