### ISSUE TITLE
Adding CMAC support

### ISSUE THREAD

**Issue by khibino** [haskell-crypto/cryptonite#74]
I want to use CMAC (Cipher based Message Authenticaton Code) with cryptonite.
I implemented a naive implementation and test vectors.

May I create a pull request for this implementation?

https://github.com/khibino/cryptonite/commit/ca0c3830ebad0eb61bb07344516a8e7fd272be03
https://github.com/khibino/cryptonite/commit/b704f2c02ad4d66395ec24b5eedc2d32bc83c6fd

>    CMAC
>      KAT - NIST test vectors
>        aes128
>          1:                 OK
>          2:                 OK
>          3:                 OK
>          4:                 OK
>          5:                 OK
>          6:                 OK
>          7:                 OK
>        aes192
>          1:                 OK
>          2:                 OK
>          3:                 OK
>          4:                 OK
>          5:                 OK
>          6:                 OK
>          7:                 OK
>        aes256
>          1:                 OK
>          2:                 OK
>          3:                 OK
>          4:                 OK
>          5:                 OK
>          6:                 OK
>          7:                 OK
>        Three Key TDEA
>          1:                 OK
>          2:                 OK
>          3:                 OK
>          4:                 OK
>          5:                 OK
>          6:                 OK (0.01s)
>          7:                 OK (0.01s)
>        Two Key TDEA
>          1:                 OK
>          2:                 OK
>          3:                 OK
>          4:                 OK
>          5:                 OK
>          6:                 OK (0.01s)
>          7:                 OK (0.01s)

**Comment by vincenthz** [comment]
yes, please.

as a pre-review, it's looking good. the only thing that strikes me is that the MAC generated should be a type not just a ByteArray constraint. Maybe something like:

```
newtype CMAC = CMAC Bytes
```

This way you can add a time equality constant function on the `Eq` instance, just like for HMAC:

```
instance Eq (HMAC a) where
    (HMAC b1) == (HMAC b2) = B.constEq b1 b2
```

**Comment by khibino** [comment]
I added CMAC newtype with cipher phantom type, and created its pull request.
https://github.com/haskell-crypto/cryptonite/pull/75
