### ISSUE TITLE
Optimized curve25519 code unused

### ISSUE THREAD

**Issue by centromere** [haskell-crypto/cryptonite#81]
[This file](https://github.com/haskell-crypto/cryptonite/blob/3656726fceafbfaeecac1a48b64c54b7f425ead3/cbits/curve25519/curve25519-donna-c64.c) is currently unused. Is support for optimized curve25519 something that can be done, or are there other issues to work around?

**Comment by vincenthz** [comment]
I think it was just a simple neglect; no reason I can think of why it's not used.
