### ISSUE TITLE
Is there a way to get minimum key size for a cipher without constructing the cipher?

### ISSUE THREAD

**Issue by slaymaker1907** [haskell-crypto/cryptonite#83]
Specifically, I would really like to not have to just remember what the minimum key size is for some particular cipher. However, it appears that the only way to do this is with cipherKeySize which seems to require an instance of a cipher to work. Is there some way to get the minimum key size for a particular cipher without calling initCipher (since that constructor may fail)?

**Comment by centromere** [comment]
```
λ> import Crypto.Cipher.Types
λ> import Crypto.Cipher.AES
λ> cipherKeySize (undefined :: AES256)
KeySizeFixed 32
```

**Comment by centromere** [comment]
Does this answer your question?

**Comment by slaymaker1907** [comment]
Thanks! That does exactly what I wanted to do.
