### ISSUE TITLE
Scrypt failures when running in parallel

### ISSUE THREAD

**Issue by afldcr** [haskell-crypto/cryptonite#91]
Simply swapping the `-rtsopts` flag in the test section of the cabal file to `-with-rtsopts=-N -threaded` causes scrypt to fail regularly.

```
> stack test --test-arguments '-j 4 --hide-successes'
/cryptonite
cryptonite-0.11: test (suite: test-cryptonite, args: -j 4 --hide-successes)

cryptonite
  KDF
    Scrypt
      2:                     FAIL (0.05s)
        expected: "\253\186\190\FS\157\&4r\NULxV\231\EM\r\SOH\233\254|j\215\203\200#x0\231svcK71b.\175\&0\217.\"\163\136o\241\t'\157\152\&0\218\199'\175\185J\131\238m\131`\203\223\162\204\ACK@"
         but got: "\235%\a|\217\CAN%\240\159\&6\138>\247\184\200\SIc6!\230\162\191\&3\137Q\206\128\216\199\184R\189$\130\225\227\202\&9\229\&6V\254\SOH$^_\171\222@Qyza\212\144\187_\245\189u\250\186\254*"
      3:                     FAIL (0.05s)
        expected: "p#\189\203:\253sHF\FS\ACK\205\129\253\&8\235\253\168\251\186\144O\142>\169\181C\246T]\161\242\213C)Ua?\SI\207b\212\151\ENQ$*\154\249\230\RS\133\220\re\RS@\223\207\SOH{EWX\135"
         but got: "\217(\243\&7z\159*\157{U\ENQ\252\&5\167\253\146E9C\f\242\182b\235y{\SO\186=n\136\247\195\SO\189\&3\230\DC1\226l\179\221\GS\146 /\224B\166c\146\240+\217\233\200\147\202\SUB \221\138\ETX\197"
      4:                     FAIL (3.92s)
        expected: "!\SOH\203\155jQ\SUB\174\173\219\190\t\207p\248\129\236V\141WJ/\253M\171\229\238\152 \173\170G\142V\253\143K\165\208\159\250\FSm\146|@\244\195\&70@I\232\169R\251\203\244\\o\167zA\164"
         but got: "\DLE#\224\217\140W\211\188X\172\194 uD\245\208\163RzU\244=\244\182w\r\DC13\192\232G`%F\208%\135p\178/b#\169N\bNo\DLEA\224\250\&4\236|e\129S+\162\174\232\139\189\175"

3 out of 626 tests failed (15.79s)

Test suite failure for package cryptonite-0.11
    test-cryptonite:  exited with: ExitFailure 1
```

This also happens in our local test suite.

Is this a problem re: running Cryptonite in a production server?

**Comment by tekul** [comment]
Hi,

I can't reproduce this locally so far. You are using version 0.11 which is a bit out of date and contains known bugs (though I'm not aware of anything that would affect SCrypt specifically). Could you
1. Confirm the problem still exists with the latest version (or at least the latest stackage snapshot), and add information on what version you have tried (and ghc version).
2. Provide details of the OS/architecture and OS version you are running on.
3. Clarify whether the failures are intermittent or they happen with every test run.

**Comment by tekul** [comment]
Ok, I can reproduce this with 0.11, so please try with an up-to-date version. The latest stackage snapshots should be OK, or you can override the version in your own build. ~~It might be due to a memory corruption bug which was reported when using SHA384~~ (It's not, since the tests fail with just the SCrypt suite).

**Comment by afldcr** [comment]
1. Just ran it against 0.16 (I accidentally checked out the version in Vincent's user's repo) and the same thing happens.

```
cryptonite-0.16: test (suite: test-cryptonite, args: -j 4 --hide-successes)

cryptonite
  KDF
    Scrypt
      3:                     FAIL (0.05s)
        expected: "p#\189\203:\253sHF\FS\ACK\205\129\253\&8\235\253\168\251\186\144O\142>\169\181C\246T]\161\242\213C)Ua?\SI\207b\212\151\ENQ$*\154\249\230\RS\133\220\re\RS@\223\207\SOH{EWX\135"
         but got: "\231Y\217\234UR\237\237\171\v\159\142\249\DC2c\156\244\128\172\175\184\DC4\a\167\DC4\230\234\140%\232\ETX\226\140CJ\148\184o5,t\ENQ\\\137\n9S?e\138\\\172\a\220`\190\132\241!\138\247W6\EOT"
      4:                     FAIL (3.97s)
        expected: "!\SOH\203\155jQ\SUB\174\173\219\190\t\207p\248\129\236V\141WJ/\253M\171\229\238\152 \173\170G\142V\253\143K\165\208\159\250\FSm\146|@\244\195\&70@I\232\169R\251\203\244\\o\167zA\164"
         but got: "F\208\239\159\233\134\204\&4z\133z\NUL\173l\215R\144Y\248'\180}\246L\137\167\n\239\US'w\211\236\191\233\&0DB\176Qo\160\EMt\163\217\132\165\212\ESC\r_\224\162\146\186\255I\225s\189\135\176\SYN"

2 out of 663 tests failed (14.67s)

Test suite failure for package cryptonite-0.16
    test-cryptonite:  exited with: ExitFailure 1
Logs printed to console
```
1. I'm running Mac OS X v10.11.4 x86-64. Our project is seeing failures on 64 bit linux and 32 bit windows CI builds, as well.
2. The failures are intermittent but frequent. Disabling parallel tasks causes no build failures.

Let me know if I can be of any more help.

**Comment by tekul** [comment]
Thanks for the info. I can now reproduce it with the master branch (also on OSX).

Just running the test executable with only the scrypt tests uncommented doesn't seem to fail often, but running with a loop gives me more-or-less immediate failures:

``` haskell
main = defaultMain $ testGroup "blah" $ map (const KAT_Scrypt.tests) [0..1000]
```

**Comment by tekul** [comment]
I think the problem was due to a short buffer being passed to the scrypt C code. Could you try with the fix I've pushed and see if it fixes the problem for you?

**Comment by afldcr** [comment]
Thanks so much @tekul! I can't seem to replicate the errors at all.

**Comment by tekul** [comment]
Great! Thanks for the report. I'll close this now and hopefully Vincent will push out a new release soon with the fix.

**Comment by vincenthz** [comment]
well spotted @tekul ! definitely will make a new release soon
