### ISSUE TITLE
bcrypt function is not pure in some circumstances

### ISSUE THREAD

**Issue by jsdw** [haskell-crypto/cryptonite#93]
I began with this:

```
import Crypto.KDF.BCrypt as Crypt
import Data.ByteString.Char8 as Bytes

let a = Crypt.bcrypt 12 (Bytes.pack "salt") (Bytes.pack "password") :: Bytes.ByteString
let b = Crypt.bcrypt 12 (Bytes.pack "salt") (Bytes.pack "password") :: Bytes.ByteString
```

Now, when I run in my ghci prompt:

```
a == b
```

I get `False` back. This is somewhat surprising and scary, since given the type signature of

```
bcrypt
  :: (memory-0.13:Data.ByteArray.Types.ByteArray salt,
      memory-0.13:Data.ByteArray.Types.ByteArray password,
      memory-0.13:Data.ByteArray.Types.ByteArray output) =>
     Int -> salt -> password -> output
```

I expected bcrypt to be a pure function. 

I expect this happens because my salt is not the desired 16 bytes in length. Indeed, trying a couple of lengths of salt, it seems to start failing when it is 11 characters or less ("saltsaltsal" was the first fail I noticed).

Perhaps the `bcrypt` function should return an `Either SomeErr output` and complain when salts are not long enough, or throw an `error` even?

**Comment by tekul** [comment]
Thanks for the report. Yes, it looks like I forgot to add the check. If you look at the doc for the function argument, it says

"The salt. Must be 16 bytes in length or an error will be raised."

So my intention was that I would call `error` if the supplied salt isn't the correct length.

**Comment by tekul** [comment]
I added the error check. Let me know if anything else crops up.
