### ISSUE TITLE
0.19 fails to build on windows

### ISSUE THREAD

**Issue by joeyh** [haskell-crypto/cryptonite#99]
[105 of 105] Compiling Crypto.Cipher.AES ( Crypto\Cipher\AES.hs, dist\build\Crypto\Cipher\AES.o )
C:\Users\jenkins\AppData\Local\Temp\ghc5168_1\ghc_2.s: Assembler messages:
C:\Users\jenkins\AppData\Local\Temp\ghc5168_1\ghc_2.s:44: Error: no such instruction: `rdrand %edx'
C:\Users\jenkins\AppData\Local\Temp\ghc5168_1\ghc_2.s:63: Error: no such instruction:`rdrand %ecx'
C:\Users\jenkins\AppData\Local\Temp\ghc5168_1\ghc_2.s:80: Error: no such instruction: `rdrand %ecx'

Hmm, the version this windows system successfully installed before is quite old: 0.7. This may not be a new breakage.

**Comment by vincenthz** [comment]
we really need an automatic CI building on windows. I'll fix the build on windows manually for now, although as a quick workaround, you can build without rdrand using the cabal flag.
